// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: yadel_controller.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Org.Roylance.Yadel {

  /// <summary>Holder for reflection information generated from yadel_controller.proto</summary>
  public static partial class YadelControllerReflection {

    #region Descriptor
    /// <summary>File descriptor for yadel_controller.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static YadelControllerReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChZ5YWRlbF9jb250cm9sbGVyLnByb3RvEhJvcmcucm95bGFuY2UueWFkZWwa",
            "EnlhZGVsX3JlcG9ydC5wcm90byJ6CgxDb21tb25BY3Rpb24SMwoHcmVxdWVz",
            "dBgBIAEoCzIiLm9yZy5yb3lsYW5jZS55YWRlbC5VSVlhZGVsUmVxdWVzdBI1",
            "CghyZXNwb25zZRgCIAEoCzIjLm9yZy5yb3lsYW5jZS55YWRlbC5VSVlhZGVs",
            "UmVzcG9uc2UitQEKEFJlcG9ydENvbnRyb2xsZXISNAoKZGVsZXRlX2RhZxgB",
            "IAEoCzIgLm9yZy5yb3lsYW5jZS55YWRlbC5Db21tb25BY3Rpb24SMQoHY3Vy",
            "cmVudBgCIAEoCzIgLm9yZy5yb3lsYW5jZS55YWRlbC5Db21tb25BY3Rpb24S",
            "OAoOZ2V0X2RhZ19zdGF0dXMYAyABKAsyIC5vcmcucm95bGFuY2UueWFkZWwu",
            "Q29tbW9uQWN0aW9uYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Org.Roylance.Yadel.YadelReportReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Org.Roylance.Yadel.CommonAction), global::Org.Roylance.Yadel.CommonAction.Parser, new[]{ "Request", "Response" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Org.Roylance.Yadel.ReportController), global::Org.Roylance.Yadel.ReportController.Parser, new[]{ "DeleteDag", "Current", "GetDagStatus" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class CommonAction : pb::IMessage<CommonAction> {
    private static readonly pb::MessageParser<CommonAction> _parser = new pb::MessageParser<CommonAction>(() => new CommonAction());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CommonAction> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Org.Roylance.Yadel.YadelControllerReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CommonAction() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CommonAction(CommonAction other) : this() {
      Request = other.request_ != null ? other.Request.Clone() : null;
      Response = other.response_ != null ? other.Response.Clone() : null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CommonAction Clone() {
      return new CommonAction(this);
    }

    /// <summary>Field number for the "request" field.</summary>
    public const int RequestFieldNumber = 1;
    private global::Org.Roylance.Yadel.UIYadelRequest request_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Org.Roylance.Yadel.UIYadelRequest Request {
      get { return request_; }
      set {
        request_ = value;
      }
    }

    /// <summary>Field number for the "response" field.</summary>
    public const int ResponseFieldNumber = 2;
    private global::Org.Roylance.Yadel.UIYadelResponse response_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Org.Roylance.Yadel.UIYadelResponse Response {
      get { return response_; }
      set {
        response_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CommonAction);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CommonAction other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Request, other.Request)) return false;
      if (!object.Equals(Response, other.Response)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (request_ != null) hash ^= Request.GetHashCode();
      if (response_ != null) hash ^= Response.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (request_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Request);
      }
      if (response_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Response);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (request_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Request);
      }
      if (response_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Response);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CommonAction other) {
      if (other == null) {
        return;
      }
      if (other.request_ != null) {
        if (request_ == null) {
          request_ = new global::Org.Roylance.Yadel.UIYadelRequest();
        }
        Request.MergeFrom(other.Request);
      }
      if (other.response_ != null) {
        if (response_ == null) {
          response_ = new global::Org.Roylance.Yadel.UIYadelResponse();
        }
        Response.MergeFrom(other.Response);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            if (request_ == null) {
              request_ = new global::Org.Roylance.Yadel.UIYadelRequest();
            }
            input.ReadMessage(request_);
            break;
          }
          case 18: {
            if (response_ == null) {
              response_ = new global::Org.Roylance.Yadel.UIYadelResponse();
            }
            input.ReadMessage(response_);
            break;
          }
        }
      }
    }

  }

  public sealed partial class ReportController : pb::IMessage<ReportController> {
    private static readonly pb::MessageParser<ReportController> _parser = new pb::MessageParser<ReportController>(() => new ReportController());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ReportController> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Org.Roylance.Yadel.YadelControllerReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ReportController() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ReportController(ReportController other) : this() {
      DeleteDag = other.deleteDag_ != null ? other.DeleteDag.Clone() : null;
      Current = other.current_ != null ? other.Current.Clone() : null;
      GetDagStatus = other.getDagStatus_ != null ? other.GetDagStatus.Clone() : null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ReportController Clone() {
      return new ReportController(this);
    }

    /// <summary>Field number for the "delete_dag" field.</summary>
    public const int DeleteDagFieldNumber = 1;
    private global::Org.Roylance.Yadel.CommonAction deleteDag_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Org.Roylance.Yadel.CommonAction DeleteDag {
      get { return deleteDag_; }
      set {
        deleteDag_ = value;
      }
    }

    /// <summary>Field number for the "current" field.</summary>
    public const int CurrentFieldNumber = 2;
    private global::Org.Roylance.Yadel.CommonAction current_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Org.Roylance.Yadel.CommonAction Current {
      get { return current_; }
      set {
        current_ = value;
      }
    }

    /// <summary>Field number for the "get_dag_status" field.</summary>
    public const int GetDagStatusFieldNumber = 3;
    private global::Org.Roylance.Yadel.CommonAction getDagStatus_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Org.Roylance.Yadel.CommonAction GetDagStatus {
      get { return getDagStatus_; }
      set {
        getDagStatus_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ReportController);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ReportController other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(DeleteDag, other.DeleteDag)) return false;
      if (!object.Equals(Current, other.Current)) return false;
      if (!object.Equals(GetDagStatus, other.GetDagStatus)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (deleteDag_ != null) hash ^= DeleteDag.GetHashCode();
      if (current_ != null) hash ^= Current.GetHashCode();
      if (getDagStatus_ != null) hash ^= GetDagStatus.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (deleteDag_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(DeleteDag);
      }
      if (current_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Current);
      }
      if (getDagStatus_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(GetDagStatus);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (deleteDag_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(DeleteDag);
      }
      if (current_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Current);
      }
      if (getDagStatus_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(GetDagStatus);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ReportController other) {
      if (other == null) {
        return;
      }
      if (other.deleteDag_ != null) {
        if (deleteDag_ == null) {
          deleteDag_ = new global::Org.Roylance.Yadel.CommonAction();
        }
        DeleteDag.MergeFrom(other.DeleteDag);
      }
      if (other.current_ != null) {
        if (current_ == null) {
          current_ = new global::Org.Roylance.Yadel.CommonAction();
        }
        Current.MergeFrom(other.Current);
      }
      if (other.getDagStatus_ != null) {
        if (getDagStatus_ == null) {
          getDagStatus_ = new global::Org.Roylance.Yadel.CommonAction();
        }
        GetDagStatus.MergeFrom(other.GetDagStatus);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            if (deleteDag_ == null) {
              deleteDag_ = new global::Org.Roylance.Yadel.CommonAction();
            }
            input.ReadMessage(deleteDag_);
            break;
          }
          case 18: {
            if (current_ == null) {
              current_ = new global::Org.Roylance.Yadel.CommonAction();
            }
            input.ReadMessage(current_);
            break;
          }
          case 26: {
            if (getDagStatus_ == null) {
              getDagStatus_ = new global::Org.Roylance.Yadel.CommonAction();
            }
            input.ReadMessage(getDagStatus_);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
