// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: yadel_controller.proto

package org.roylance.yadel;

public final class YadelController {
  private YadelController() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CommonActionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.roylance.yadel.CommonAction)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .org.roylance.yadel.UIYadelRequest request = 1;</code>
     */
    boolean hasRequest();
    /**
     * <code>optional .org.roylance.yadel.UIYadelRequest request = 1;</code>
     */
    org.roylance.yadel.YadelReport.UIYadelRequest getRequest();
    /**
     * <code>optional .org.roylance.yadel.UIYadelRequest request = 1;</code>
     */
    org.roylance.yadel.YadelReport.UIYadelRequestOrBuilder getRequestOrBuilder();

    /**
     * <code>optional .org.roylance.yadel.UIYadelResponse response = 2;</code>
     */
    boolean hasResponse();
    /**
     * <code>optional .org.roylance.yadel.UIYadelResponse response = 2;</code>
     */
    org.roylance.yadel.YadelReport.UIYadelResponse getResponse();
    /**
     * <code>optional .org.roylance.yadel.UIYadelResponse response = 2;</code>
     */
    org.roylance.yadel.YadelReport.UIYadelResponseOrBuilder getResponseOrBuilder();
  }
  /**
   * Protobuf type {@code org.roylance.yadel.CommonAction}
   */
  public  static final class CommonAction extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.roylance.yadel.CommonAction)
      CommonActionOrBuilder {
    // Use CommonAction.newBuilder() to construct.
    private CommonAction(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CommonAction() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private CommonAction(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              org.roylance.yadel.YadelReport.UIYadelRequest.Builder subBuilder = null;
              if (request_ != null) {
                subBuilder = request_.toBuilder();
              }
              request_ = input.readMessage(org.roylance.yadel.YadelReport.UIYadelRequest.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(request_);
                request_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              org.roylance.yadel.YadelReport.UIYadelResponse.Builder subBuilder = null;
              if (response_ != null) {
                subBuilder = response_.toBuilder();
              }
              response_ = input.readMessage(org.roylance.yadel.YadelReport.UIYadelResponse.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(response_);
                response_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.roylance.yadel.YadelController.internal_static_org_roylance_yadel_CommonAction_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.roylance.yadel.YadelController.internal_static_org_roylance_yadel_CommonAction_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.roylance.yadel.YadelController.CommonAction.class, org.roylance.yadel.YadelController.CommonAction.Builder.class);
    }

    public static final int REQUEST_FIELD_NUMBER = 1;
    private org.roylance.yadel.YadelReport.UIYadelRequest request_;
    /**
     * <code>optional .org.roylance.yadel.UIYadelRequest request = 1;</code>
     */
    public boolean hasRequest() {
      return request_ != null;
    }
    /**
     * <code>optional .org.roylance.yadel.UIYadelRequest request = 1;</code>
     */
    public org.roylance.yadel.YadelReport.UIYadelRequest getRequest() {
      return request_ == null ? org.roylance.yadel.YadelReport.UIYadelRequest.getDefaultInstance() : request_;
    }
    /**
     * <code>optional .org.roylance.yadel.UIYadelRequest request = 1;</code>
     */
    public org.roylance.yadel.YadelReport.UIYadelRequestOrBuilder getRequestOrBuilder() {
      return getRequest();
    }

    public static final int RESPONSE_FIELD_NUMBER = 2;
    private org.roylance.yadel.YadelReport.UIYadelResponse response_;
    /**
     * <code>optional .org.roylance.yadel.UIYadelResponse response = 2;</code>
     */
    public boolean hasResponse() {
      return response_ != null;
    }
    /**
     * <code>optional .org.roylance.yadel.UIYadelResponse response = 2;</code>
     */
    public org.roylance.yadel.YadelReport.UIYadelResponse getResponse() {
      return response_ == null ? org.roylance.yadel.YadelReport.UIYadelResponse.getDefaultInstance() : response_;
    }
    /**
     * <code>optional .org.roylance.yadel.UIYadelResponse response = 2;</code>
     */
    public org.roylance.yadel.YadelReport.UIYadelResponseOrBuilder getResponseOrBuilder() {
      return getResponse();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (request_ != null) {
        output.writeMessage(1, getRequest());
      }
      if (response_ != null) {
        output.writeMessage(2, getResponse());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (request_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getRequest());
      }
      if (response_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getResponse());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.roylance.yadel.YadelController.CommonAction)) {
        return super.equals(obj);
      }
      org.roylance.yadel.YadelController.CommonAction other = (org.roylance.yadel.YadelController.CommonAction) obj;

      boolean result = true;
      result = result && (hasRequest() == other.hasRequest());
      if (hasRequest()) {
        result = result && getRequest()
            .equals(other.getRequest());
      }
      result = result && (hasResponse() == other.hasResponse());
      if (hasResponse()) {
        result = result && getResponse()
            .equals(other.getResponse());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasRequest()) {
        hash = (37 * hash) + REQUEST_FIELD_NUMBER;
        hash = (53 * hash) + getRequest().hashCode();
      }
      if (hasResponse()) {
        hash = (37 * hash) + RESPONSE_FIELD_NUMBER;
        hash = (53 * hash) + getResponse().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.roylance.yadel.YadelController.CommonAction parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.roylance.yadel.YadelController.CommonAction parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.roylance.yadel.YadelController.CommonAction parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.roylance.yadel.YadelController.CommonAction parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.roylance.yadel.YadelController.CommonAction parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.roylance.yadel.YadelController.CommonAction parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.roylance.yadel.YadelController.CommonAction parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.roylance.yadel.YadelController.CommonAction parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.roylance.yadel.YadelController.CommonAction parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.roylance.yadel.YadelController.CommonAction parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.roylance.yadel.YadelController.CommonAction prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.roylance.yadel.CommonAction}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.roylance.yadel.CommonAction)
        org.roylance.yadel.YadelController.CommonActionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.roylance.yadel.YadelController.internal_static_org_roylance_yadel_CommonAction_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.roylance.yadel.YadelController.internal_static_org_roylance_yadel_CommonAction_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.roylance.yadel.YadelController.CommonAction.class, org.roylance.yadel.YadelController.CommonAction.Builder.class);
      }

      // Construct using org.roylance.yadel.YadelController.CommonAction.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (requestBuilder_ == null) {
          request_ = null;
        } else {
          request_ = null;
          requestBuilder_ = null;
        }
        if (responseBuilder_ == null) {
          response_ = null;
        } else {
          response_ = null;
          responseBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.roylance.yadel.YadelController.internal_static_org_roylance_yadel_CommonAction_descriptor;
      }

      public org.roylance.yadel.YadelController.CommonAction getDefaultInstanceForType() {
        return org.roylance.yadel.YadelController.CommonAction.getDefaultInstance();
      }

      public org.roylance.yadel.YadelController.CommonAction build() {
        org.roylance.yadel.YadelController.CommonAction result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.roylance.yadel.YadelController.CommonAction buildPartial() {
        org.roylance.yadel.YadelController.CommonAction result = new org.roylance.yadel.YadelController.CommonAction(this);
        if (requestBuilder_ == null) {
          result.request_ = request_;
        } else {
          result.request_ = requestBuilder_.build();
        }
        if (responseBuilder_ == null) {
          result.response_ = response_;
        } else {
          result.response_ = responseBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.roylance.yadel.YadelController.CommonAction) {
          return mergeFrom((org.roylance.yadel.YadelController.CommonAction)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.roylance.yadel.YadelController.CommonAction other) {
        if (other == org.roylance.yadel.YadelController.CommonAction.getDefaultInstance()) return this;
        if (other.hasRequest()) {
          mergeRequest(other.getRequest());
        }
        if (other.hasResponse()) {
          mergeResponse(other.getResponse());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.roylance.yadel.YadelController.CommonAction parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.roylance.yadel.YadelController.CommonAction) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private org.roylance.yadel.YadelReport.UIYadelRequest request_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          org.roylance.yadel.YadelReport.UIYadelRequest, org.roylance.yadel.YadelReport.UIYadelRequest.Builder, org.roylance.yadel.YadelReport.UIYadelRequestOrBuilder> requestBuilder_;
      /**
       * <code>optional .org.roylance.yadel.UIYadelRequest request = 1;</code>
       */
      public boolean hasRequest() {
        return requestBuilder_ != null || request_ != null;
      }
      /**
       * <code>optional .org.roylance.yadel.UIYadelRequest request = 1;</code>
       */
      public org.roylance.yadel.YadelReport.UIYadelRequest getRequest() {
        if (requestBuilder_ == null) {
          return request_ == null ? org.roylance.yadel.YadelReport.UIYadelRequest.getDefaultInstance() : request_;
        } else {
          return requestBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .org.roylance.yadel.UIYadelRequest request = 1;</code>
       */
      public Builder setRequest(org.roylance.yadel.YadelReport.UIYadelRequest value) {
        if (requestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          request_ = value;
          onChanged();
        } else {
          requestBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .org.roylance.yadel.UIYadelRequest request = 1;</code>
       */
      public Builder setRequest(
          org.roylance.yadel.YadelReport.UIYadelRequest.Builder builderForValue) {
        if (requestBuilder_ == null) {
          request_ = builderForValue.build();
          onChanged();
        } else {
          requestBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .org.roylance.yadel.UIYadelRequest request = 1;</code>
       */
      public Builder mergeRequest(org.roylance.yadel.YadelReport.UIYadelRequest value) {
        if (requestBuilder_ == null) {
          if (request_ != null) {
            request_ =
              org.roylance.yadel.YadelReport.UIYadelRequest.newBuilder(request_).mergeFrom(value).buildPartial();
          } else {
            request_ = value;
          }
          onChanged();
        } else {
          requestBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .org.roylance.yadel.UIYadelRequest request = 1;</code>
       */
      public Builder clearRequest() {
        if (requestBuilder_ == null) {
          request_ = null;
          onChanged();
        } else {
          request_ = null;
          requestBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .org.roylance.yadel.UIYadelRequest request = 1;</code>
       */
      public org.roylance.yadel.YadelReport.UIYadelRequest.Builder getRequestBuilder() {
        
        onChanged();
        return getRequestFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .org.roylance.yadel.UIYadelRequest request = 1;</code>
       */
      public org.roylance.yadel.YadelReport.UIYadelRequestOrBuilder getRequestOrBuilder() {
        if (requestBuilder_ != null) {
          return requestBuilder_.getMessageOrBuilder();
        } else {
          return request_ == null ?
              org.roylance.yadel.YadelReport.UIYadelRequest.getDefaultInstance() : request_;
        }
      }
      /**
       * <code>optional .org.roylance.yadel.UIYadelRequest request = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          org.roylance.yadel.YadelReport.UIYadelRequest, org.roylance.yadel.YadelReport.UIYadelRequest.Builder, org.roylance.yadel.YadelReport.UIYadelRequestOrBuilder> 
          getRequestFieldBuilder() {
        if (requestBuilder_ == null) {
          requestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              org.roylance.yadel.YadelReport.UIYadelRequest, org.roylance.yadel.YadelReport.UIYadelRequest.Builder, org.roylance.yadel.YadelReport.UIYadelRequestOrBuilder>(
                  getRequest(),
                  getParentForChildren(),
                  isClean());
          request_ = null;
        }
        return requestBuilder_;
      }

      private org.roylance.yadel.YadelReport.UIYadelResponse response_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          org.roylance.yadel.YadelReport.UIYadelResponse, org.roylance.yadel.YadelReport.UIYadelResponse.Builder, org.roylance.yadel.YadelReport.UIYadelResponseOrBuilder> responseBuilder_;
      /**
       * <code>optional .org.roylance.yadel.UIYadelResponse response = 2;</code>
       */
      public boolean hasResponse() {
        return responseBuilder_ != null || response_ != null;
      }
      /**
       * <code>optional .org.roylance.yadel.UIYadelResponse response = 2;</code>
       */
      public org.roylance.yadel.YadelReport.UIYadelResponse getResponse() {
        if (responseBuilder_ == null) {
          return response_ == null ? org.roylance.yadel.YadelReport.UIYadelResponse.getDefaultInstance() : response_;
        } else {
          return responseBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .org.roylance.yadel.UIYadelResponse response = 2;</code>
       */
      public Builder setResponse(org.roylance.yadel.YadelReport.UIYadelResponse value) {
        if (responseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          response_ = value;
          onChanged();
        } else {
          responseBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .org.roylance.yadel.UIYadelResponse response = 2;</code>
       */
      public Builder setResponse(
          org.roylance.yadel.YadelReport.UIYadelResponse.Builder builderForValue) {
        if (responseBuilder_ == null) {
          response_ = builderForValue.build();
          onChanged();
        } else {
          responseBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .org.roylance.yadel.UIYadelResponse response = 2;</code>
       */
      public Builder mergeResponse(org.roylance.yadel.YadelReport.UIYadelResponse value) {
        if (responseBuilder_ == null) {
          if (response_ != null) {
            response_ =
              org.roylance.yadel.YadelReport.UIYadelResponse.newBuilder(response_).mergeFrom(value).buildPartial();
          } else {
            response_ = value;
          }
          onChanged();
        } else {
          responseBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .org.roylance.yadel.UIYadelResponse response = 2;</code>
       */
      public Builder clearResponse() {
        if (responseBuilder_ == null) {
          response_ = null;
          onChanged();
        } else {
          response_ = null;
          responseBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .org.roylance.yadel.UIYadelResponse response = 2;</code>
       */
      public org.roylance.yadel.YadelReport.UIYadelResponse.Builder getResponseBuilder() {
        
        onChanged();
        return getResponseFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .org.roylance.yadel.UIYadelResponse response = 2;</code>
       */
      public org.roylance.yadel.YadelReport.UIYadelResponseOrBuilder getResponseOrBuilder() {
        if (responseBuilder_ != null) {
          return responseBuilder_.getMessageOrBuilder();
        } else {
          return response_ == null ?
              org.roylance.yadel.YadelReport.UIYadelResponse.getDefaultInstance() : response_;
        }
      }
      /**
       * <code>optional .org.roylance.yadel.UIYadelResponse response = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          org.roylance.yadel.YadelReport.UIYadelResponse, org.roylance.yadel.YadelReport.UIYadelResponse.Builder, org.roylance.yadel.YadelReport.UIYadelResponseOrBuilder> 
          getResponseFieldBuilder() {
        if (responseBuilder_ == null) {
          responseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              org.roylance.yadel.YadelReport.UIYadelResponse, org.roylance.yadel.YadelReport.UIYadelResponse.Builder, org.roylance.yadel.YadelReport.UIYadelResponseOrBuilder>(
                  getResponse(),
                  getParentForChildren(),
                  isClean());
          response_ = null;
        }
        return responseBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:org.roylance.yadel.CommonAction)
    }

    // @@protoc_insertion_point(class_scope:org.roylance.yadel.CommonAction)
    private static final org.roylance.yadel.YadelController.CommonAction DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.roylance.yadel.YadelController.CommonAction();
    }

    public static org.roylance.yadel.YadelController.CommonAction getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CommonAction>
        PARSER = new com.google.protobuf.AbstractParser<CommonAction>() {
      public CommonAction parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new CommonAction(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CommonAction> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CommonAction> getParserForType() {
      return PARSER;
    }

    public org.roylance.yadel.YadelController.CommonAction getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ReportControllerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.roylance.yadel.ReportController)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .org.roylance.yadel.CommonAction delete_dag = 1;</code>
     */
    boolean hasDeleteDag();
    /**
     * <code>optional .org.roylance.yadel.CommonAction delete_dag = 1;</code>
     */
    org.roylance.yadel.YadelController.CommonAction getDeleteDag();
    /**
     * <code>optional .org.roylance.yadel.CommonAction delete_dag = 1;</code>
     */
    org.roylance.yadel.YadelController.CommonActionOrBuilder getDeleteDagOrBuilder();

    /**
     * <code>optional .org.roylance.yadel.CommonAction current = 2;</code>
     */
    boolean hasCurrent();
    /**
     * <code>optional .org.roylance.yadel.CommonAction current = 2;</code>
     */
    org.roylance.yadel.YadelController.CommonAction getCurrent();
    /**
     * <code>optional .org.roylance.yadel.CommonAction current = 2;</code>
     */
    org.roylance.yadel.YadelController.CommonActionOrBuilder getCurrentOrBuilder();
  }
  /**
   * Protobuf type {@code org.roylance.yadel.ReportController}
   */
  public  static final class ReportController extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.roylance.yadel.ReportController)
      ReportControllerOrBuilder {
    // Use ReportController.newBuilder() to construct.
    private ReportController(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ReportController() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ReportController(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              org.roylance.yadel.YadelController.CommonAction.Builder subBuilder = null;
              if (deleteDag_ != null) {
                subBuilder = deleteDag_.toBuilder();
              }
              deleteDag_ = input.readMessage(org.roylance.yadel.YadelController.CommonAction.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(deleteDag_);
                deleteDag_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              org.roylance.yadel.YadelController.CommonAction.Builder subBuilder = null;
              if (current_ != null) {
                subBuilder = current_.toBuilder();
              }
              current_ = input.readMessage(org.roylance.yadel.YadelController.CommonAction.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(current_);
                current_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.roylance.yadel.YadelController.internal_static_org_roylance_yadel_ReportController_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.roylance.yadel.YadelController.internal_static_org_roylance_yadel_ReportController_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.roylance.yadel.YadelController.ReportController.class, org.roylance.yadel.YadelController.ReportController.Builder.class);
    }

    public static final int DELETE_DAG_FIELD_NUMBER = 1;
    private org.roylance.yadel.YadelController.CommonAction deleteDag_;
    /**
     * <code>optional .org.roylance.yadel.CommonAction delete_dag = 1;</code>
     */
    public boolean hasDeleteDag() {
      return deleteDag_ != null;
    }
    /**
     * <code>optional .org.roylance.yadel.CommonAction delete_dag = 1;</code>
     */
    public org.roylance.yadel.YadelController.CommonAction getDeleteDag() {
      return deleteDag_ == null ? org.roylance.yadel.YadelController.CommonAction.getDefaultInstance() : deleteDag_;
    }
    /**
     * <code>optional .org.roylance.yadel.CommonAction delete_dag = 1;</code>
     */
    public org.roylance.yadel.YadelController.CommonActionOrBuilder getDeleteDagOrBuilder() {
      return getDeleteDag();
    }

    public static final int CURRENT_FIELD_NUMBER = 2;
    private org.roylance.yadel.YadelController.CommonAction current_;
    /**
     * <code>optional .org.roylance.yadel.CommonAction current = 2;</code>
     */
    public boolean hasCurrent() {
      return current_ != null;
    }
    /**
     * <code>optional .org.roylance.yadel.CommonAction current = 2;</code>
     */
    public org.roylance.yadel.YadelController.CommonAction getCurrent() {
      return current_ == null ? org.roylance.yadel.YadelController.CommonAction.getDefaultInstance() : current_;
    }
    /**
     * <code>optional .org.roylance.yadel.CommonAction current = 2;</code>
     */
    public org.roylance.yadel.YadelController.CommonActionOrBuilder getCurrentOrBuilder() {
      return getCurrent();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (deleteDag_ != null) {
        output.writeMessage(1, getDeleteDag());
      }
      if (current_ != null) {
        output.writeMessage(2, getCurrent());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (deleteDag_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getDeleteDag());
      }
      if (current_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getCurrent());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.roylance.yadel.YadelController.ReportController)) {
        return super.equals(obj);
      }
      org.roylance.yadel.YadelController.ReportController other = (org.roylance.yadel.YadelController.ReportController) obj;

      boolean result = true;
      result = result && (hasDeleteDag() == other.hasDeleteDag());
      if (hasDeleteDag()) {
        result = result && getDeleteDag()
            .equals(other.getDeleteDag());
      }
      result = result && (hasCurrent() == other.hasCurrent());
      if (hasCurrent()) {
        result = result && getCurrent()
            .equals(other.getCurrent());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasDeleteDag()) {
        hash = (37 * hash) + DELETE_DAG_FIELD_NUMBER;
        hash = (53 * hash) + getDeleteDag().hashCode();
      }
      if (hasCurrent()) {
        hash = (37 * hash) + CURRENT_FIELD_NUMBER;
        hash = (53 * hash) + getCurrent().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.roylance.yadel.YadelController.ReportController parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.roylance.yadel.YadelController.ReportController parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.roylance.yadel.YadelController.ReportController parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.roylance.yadel.YadelController.ReportController parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.roylance.yadel.YadelController.ReportController parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.roylance.yadel.YadelController.ReportController parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.roylance.yadel.YadelController.ReportController parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.roylance.yadel.YadelController.ReportController parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.roylance.yadel.YadelController.ReportController parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.roylance.yadel.YadelController.ReportController parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.roylance.yadel.YadelController.ReportController prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.roylance.yadel.ReportController}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.roylance.yadel.ReportController)
        org.roylance.yadel.YadelController.ReportControllerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.roylance.yadel.YadelController.internal_static_org_roylance_yadel_ReportController_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.roylance.yadel.YadelController.internal_static_org_roylance_yadel_ReportController_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.roylance.yadel.YadelController.ReportController.class, org.roylance.yadel.YadelController.ReportController.Builder.class);
      }

      // Construct using org.roylance.yadel.YadelController.ReportController.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (deleteDagBuilder_ == null) {
          deleteDag_ = null;
        } else {
          deleteDag_ = null;
          deleteDagBuilder_ = null;
        }
        if (currentBuilder_ == null) {
          current_ = null;
        } else {
          current_ = null;
          currentBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.roylance.yadel.YadelController.internal_static_org_roylance_yadel_ReportController_descriptor;
      }

      public org.roylance.yadel.YadelController.ReportController getDefaultInstanceForType() {
        return org.roylance.yadel.YadelController.ReportController.getDefaultInstance();
      }

      public org.roylance.yadel.YadelController.ReportController build() {
        org.roylance.yadel.YadelController.ReportController result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.roylance.yadel.YadelController.ReportController buildPartial() {
        org.roylance.yadel.YadelController.ReportController result = new org.roylance.yadel.YadelController.ReportController(this);
        if (deleteDagBuilder_ == null) {
          result.deleteDag_ = deleteDag_;
        } else {
          result.deleteDag_ = deleteDagBuilder_.build();
        }
        if (currentBuilder_ == null) {
          result.current_ = current_;
        } else {
          result.current_ = currentBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.roylance.yadel.YadelController.ReportController) {
          return mergeFrom((org.roylance.yadel.YadelController.ReportController)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.roylance.yadel.YadelController.ReportController other) {
        if (other == org.roylance.yadel.YadelController.ReportController.getDefaultInstance()) return this;
        if (other.hasDeleteDag()) {
          mergeDeleteDag(other.getDeleteDag());
        }
        if (other.hasCurrent()) {
          mergeCurrent(other.getCurrent());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.roylance.yadel.YadelController.ReportController parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.roylance.yadel.YadelController.ReportController) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private org.roylance.yadel.YadelController.CommonAction deleteDag_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          org.roylance.yadel.YadelController.CommonAction, org.roylance.yadel.YadelController.CommonAction.Builder, org.roylance.yadel.YadelController.CommonActionOrBuilder> deleteDagBuilder_;
      /**
       * <code>optional .org.roylance.yadel.CommonAction delete_dag = 1;</code>
       */
      public boolean hasDeleteDag() {
        return deleteDagBuilder_ != null || deleteDag_ != null;
      }
      /**
       * <code>optional .org.roylance.yadel.CommonAction delete_dag = 1;</code>
       */
      public org.roylance.yadel.YadelController.CommonAction getDeleteDag() {
        if (deleteDagBuilder_ == null) {
          return deleteDag_ == null ? org.roylance.yadel.YadelController.CommonAction.getDefaultInstance() : deleteDag_;
        } else {
          return deleteDagBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .org.roylance.yadel.CommonAction delete_dag = 1;</code>
       */
      public Builder setDeleteDag(org.roylance.yadel.YadelController.CommonAction value) {
        if (deleteDagBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          deleteDag_ = value;
          onChanged();
        } else {
          deleteDagBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .org.roylance.yadel.CommonAction delete_dag = 1;</code>
       */
      public Builder setDeleteDag(
          org.roylance.yadel.YadelController.CommonAction.Builder builderForValue) {
        if (deleteDagBuilder_ == null) {
          deleteDag_ = builderForValue.build();
          onChanged();
        } else {
          deleteDagBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .org.roylance.yadel.CommonAction delete_dag = 1;</code>
       */
      public Builder mergeDeleteDag(org.roylance.yadel.YadelController.CommonAction value) {
        if (deleteDagBuilder_ == null) {
          if (deleteDag_ != null) {
            deleteDag_ =
              org.roylance.yadel.YadelController.CommonAction.newBuilder(deleteDag_).mergeFrom(value).buildPartial();
          } else {
            deleteDag_ = value;
          }
          onChanged();
        } else {
          deleteDagBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .org.roylance.yadel.CommonAction delete_dag = 1;</code>
       */
      public Builder clearDeleteDag() {
        if (deleteDagBuilder_ == null) {
          deleteDag_ = null;
          onChanged();
        } else {
          deleteDag_ = null;
          deleteDagBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .org.roylance.yadel.CommonAction delete_dag = 1;</code>
       */
      public org.roylance.yadel.YadelController.CommonAction.Builder getDeleteDagBuilder() {
        
        onChanged();
        return getDeleteDagFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .org.roylance.yadel.CommonAction delete_dag = 1;</code>
       */
      public org.roylance.yadel.YadelController.CommonActionOrBuilder getDeleteDagOrBuilder() {
        if (deleteDagBuilder_ != null) {
          return deleteDagBuilder_.getMessageOrBuilder();
        } else {
          return deleteDag_ == null ?
              org.roylance.yadel.YadelController.CommonAction.getDefaultInstance() : deleteDag_;
        }
      }
      /**
       * <code>optional .org.roylance.yadel.CommonAction delete_dag = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          org.roylance.yadel.YadelController.CommonAction, org.roylance.yadel.YadelController.CommonAction.Builder, org.roylance.yadel.YadelController.CommonActionOrBuilder> 
          getDeleteDagFieldBuilder() {
        if (deleteDagBuilder_ == null) {
          deleteDagBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              org.roylance.yadel.YadelController.CommonAction, org.roylance.yadel.YadelController.CommonAction.Builder, org.roylance.yadel.YadelController.CommonActionOrBuilder>(
                  getDeleteDag(),
                  getParentForChildren(),
                  isClean());
          deleteDag_ = null;
        }
        return deleteDagBuilder_;
      }

      private org.roylance.yadel.YadelController.CommonAction current_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          org.roylance.yadel.YadelController.CommonAction, org.roylance.yadel.YadelController.CommonAction.Builder, org.roylance.yadel.YadelController.CommonActionOrBuilder> currentBuilder_;
      /**
       * <code>optional .org.roylance.yadel.CommonAction current = 2;</code>
       */
      public boolean hasCurrent() {
        return currentBuilder_ != null || current_ != null;
      }
      /**
       * <code>optional .org.roylance.yadel.CommonAction current = 2;</code>
       */
      public org.roylance.yadel.YadelController.CommonAction getCurrent() {
        if (currentBuilder_ == null) {
          return current_ == null ? org.roylance.yadel.YadelController.CommonAction.getDefaultInstance() : current_;
        } else {
          return currentBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .org.roylance.yadel.CommonAction current = 2;</code>
       */
      public Builder setCurrent(org.roylance.yadel.YadelController.CommonAction value) {
        if (currentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          current_ = value;
          onChanged();
        } else {
          currentBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .org.roylance.yadel.CommonAction current = 2;</code>
       */
      public Builder setCurrent(
          org.roylance.yadel.YadelController.CommonAction.Builder builderForValue) {
        if (currentBuilder_ == null) {
          current_ = builderForValue.build();
          onChanged();
        } else {
          currentBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .org.roylance.yadel.CommonAction current = 2;</code>
       */
      public Builder mergeCurrent(org.roylance.yadel.YadelController.CommonAction value) {
        if (currentBuilder_ == null) {
          if (current_ != null) {
            current_ =
              org.roylance.yadel.YadelController.CommonAction.newBuilder(current_).mergeFrom(value).buildPartial();
          } else {
            current_ = value;
          }
          onChanged();
        } else {
          currentBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .org.roylance.yadel.CommonAction current = 2;</code>
       */
      public Builder clearCurrent() {
        if (currentBuilder_ == null) {
          current_ = null;
          onChanged();
        } else {
          current_ = null;
          currentBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .org.roylance.yadel.CommonAction current = 2;</code>
       */
      public org.roylance.yadel.YadelController.CommonAction.Builder getCurrentBuilder() {
        
        onChanged();
        return getCurrentFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .org.roylance.yadel.CommonAction current = 2;</code>
       */
      public org.roylance.yadel.YadelController.CommonActionOrBuilder getCurrentOrBuilder() {
        if (currentBuilder_ != null) {
          return currentBuilder_.getMessageOrBuilder();
        } else {
          return current_ == null ?
              org.roylance.yadel.YadelController.CommonAction.getDefaultInstance() : current_;
        }
      }
      /**
       * <code>optional .org.roylance.yadel.CommonAction current = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          org.roylance.yadel.YadelController.CommonAction, org.roylance.yadel.YadelController.CommonAction.Builder, org.roylance.yadel.YadelController.CommonActionOrBuilder> 
          getCurrentFieldBuilder() {
        if (currentBuilder_ == null) {
          currentBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              org.roylance.yadel.YadelController.CommonAction, org.roylance.yadel.YadelController.CommonAction.Builder, org.roylance.yadel.YadelController.CommonActionOrBuilder>(
                  getCurrent(),
                  getParentForChildren(),
                  isClean());
          current_ = null;
        }
        return currentBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:org.roylance.yadel.ReportController)
    }

    // @@protoc_insertion_point(class_scope:org.roylance.yadel.ReportController)
    private static final org.roylance.yadel.YadelController.ReportController DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.roylance.yadel.YadelController.ReportController();
    }

    public static org.roylance.yadel.YadelController.ReportController getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ReportController>
        PARSER = new com.google.protobuf.AbstractParser<ReportController>() {
      public ReportController parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ReportController(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ReportController> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ReportController> getParserForType() {
      return PARSER;
    }

    public org.roylance.yadel.YadelController.ReportController getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_roylance_yadel_CommonAction_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_roylance_yadel_CommonAction_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_roylance_yadel_ReportController_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_roylance_yadel_ReportController_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026yadel_controller.proto\022\022org.roylance.y" +
      "adel\032\022yadel_report.proto\"z\n\014CommonAction" +
      "\0223\n\007request\030\001 \001(\0132\".org.roylance.yadel.U" +
      "IYadelRequest\0225\n\010response\030\002 \001(\0132#.org.ro" +
      "ylance.yadel.UIYadelResponse\"{\n\020ReportCo" +
      "ntroller\0224\n\ndelete_dag\030\001 \001(\0132 .org.royla" +
      "nce.yadel.CommonAction\0221\n\007current\030\002 \001(\0132" +
      " .org.roylance.yadel.CommonActionb\006proto" +
      "3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.roylance.yadel.YadelReport.getDescriptor(),
        }, assigner);
    internal_static_org_roylance_yadel_CommonAction_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_roylance_yadel_CommonAction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_roylance_yadel_CommonAction_descriptor,
        new java.lang.String[] { "Request", "Response", });
    internal_static_org_roylance_yadel_ReportController_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_roylance_yadel_ReportController_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_roylance_yadel_ReportController_descriptor,
        new java.lang.String[] { "DeleteDag", "Current", });
    org.roylance.yadel.YadelReport.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
