// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: yadel_controller.proto

package org.roylance.yadel;

public final class YadelController {
  private YadelController() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CommonActionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.roylance.yadel.CommonAction)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .org.roylance.yadel.UIRequest request = 1;</code>
     */
    boolean hasRequest();
    /**
     * <code>optional .org.roylance.yadel.UIRequest request = 1;</code>
     */
    org.roylance.yadel.YadelReport.UIRequest getRequest();
    /**
     * <code>optional .org.roylance.yadel.UIRequest request = 1;</code>
     */
    org.roylance.yadel.YadelReport.UIRequestOrBuilder getRequestOrBuilder();

    /**
     * <code>optional .org.roylance.yadel.UIResponse response = 2;</code>
     */
    boolean hasResponse();
    /**
     * <code>optional .org.roylance.yadel.UIResponse response = 2;</code>
     */
    org.roylance.yadel.YadelReport.UIResponse getResponse();
    /**
     * <code>optional .org.roylance.yadel.UIResponse response = 2;</code>
     */
    org.roylance.yadel.YadelReport.UIResponseOrBuilder getResponseOrBuilder();
  }
  /**
   * Protobuf type {@code org.roylance.yadel.CommonAction}
   */
  public static final class CommonAction extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:org.roylance.yadel.CommonAction)
      CommonActionOrBuilder {
    // Use CommonAction.newBuilder() to construct.
    private CommonAction(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CommonAction(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CommonAction defaultInstance;
    public static CommonAction getDefaultInstance() {
      return defaultInstance;
    }

    public CommonAction getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CommonAction(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              org.roylance.yadel.YadelReport.UIRequest.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = request_.toBuilder();
              }
              request_ = input.readMessage(org.roylance.yadel.YadelReport.UIRequest.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(request_);
                request_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              org.roylance.yadel.YadelReport.UIResponse.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = response_.toBuilder();
              }
              response_ = input.readMessage(org.roylance.yadel.YadelReport.UIResponse.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(response_);
                response_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.roylance.yadel.YadelController.internal_static_org_roylance_yadel_CommonAction_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.roylance.yadel.YadelController.internal_static_org_roylance_yadel_CommonAction_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.roylance.yadel.YadelController.CommonAction.class, org.roylance.yadel.YadelController.CommonAction.Builder.class);
    }

    public static com.google.protobuf.Parser<CommonAction> PARSER =
        new com.google.protobuf.AbstractParser<CommonAction>() {
      public CommonAction parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CommonAction(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CommonAction> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int REQUEST_FIELD_NUMBER = 1;
    private org.roylance.yadel.YadelReport.UIRequest request_;
    /**
     * <code>optional .org.roylance.yadel.UIRequest request = 1;</code>
     */
    public boolean hasRequest() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .org.roylance.yadel.UIRequest request = 1;</code>
     */
    public org.roylance.yadel.YadelReport.UIRequest getRequest() {
      return request_;
    }
    /**
     * <code>optional .org.roylance.yadel.UIRequest request = 1;</code>
     */
    public org.roylance.yadel.YadelReport.UIRequestOrBuilder getRequestOrBuilder() {
      return request_;
    }

    public static final int RESPONSE_FIELD_NUMBER = 2;
    private org.roylance.yadel.YadelReport.UIResponse response_;
    /**
     * <code>optional .org.roylance.yadel.UIResponse response = 2;</code>
     */
    public boolean hasResponse() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .org.roylance.yadel.UIResponse response = 2;</code>
     */
    public org.roylance.yadel.YadelReport.UIResponse getResponse() {
      return response_;
    }
    /**
     * <code>optional .org.roylance.yadel.UIResponse response = 2;</code>
     */
    public org.roylance.yadel.YadelReport.UIResponseOrBuilder getResponseOrBuilder() {
      return response_;
    }

    private void initFields() {
      request_ = org.roylance.yadel.YadelReport.UIRequest.getDefaultInstance();
      response_ = org.roylance.yadel.YadelReport.UIResponse.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, request_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, response_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, request_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, response_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.roylance.yadel.YadelController.CommonAction parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.roylance.yadel.YadelController.CommonAction parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.roylance.yadel.YadelController.CommonAction parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.roylance.yadel.YadelController.CommonAction parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.roylance.yadel.YadelController.CommonAction parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.roylance.yadel.YadelController.CommonAction parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.roylance.yadel.YadelController.CommonAction parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.roylance.yadel.YadelController.CommonAction parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.roylance.yadel.YadelController.CommonAction parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.roylance.yadel.YadelController.CommonAction parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.roylance.yadel.YadelController.CommonAction prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.roylance.yadel.CommonAction}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.roylance.yadel.CommonAction)
        org.roylance.yadel.YadelController.CommonActionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.roylance.yadel.YadelController.internal_static_org_roylance_yadel_CommonAction_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.roylance.yadel.YadelController.internal_static_org_roylance_yadel_CommonAction_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.roylance.yadel.YadelController.CommonAction.class, org.roylance.yadel.YadelController.CommonAction.Builder.class);
      }

      // Construct using org.roylance.yadel.YadelController.CommonAction.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getRequestFieldBuilder();
          getResponseFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (requestBuilder_ == null) {
          request_ = org.roylance.yadel.YadelReport.UIRequest.getDefaultInstance();
        } else {
          requestBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (responseBuilder_ == null) {
          response_ = org.roylance.yadel.YadelReport.UIResponse.getDefaultInstance();
        } else {
          responseBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.roylance.yadel.YadelController.internal_static_org_roylance_yadel_CommonAction_descriptor;
      }

      public org.roylance.yadel.YadelController.CommonAction getDefaultInstanceForType() {
        return org.roylance.yadel.YadelController.CommonAction.getDefaultInstance();
      }

      public org.roylance.yadel.YadelController.CommonAction build() {
        org.roylance.yadel.YadelController.CommonAction result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.roylance.yadel.YadelController.CommonAction buildPartial() {
        org.roylance.yadel.YadelController.CommonAction result = new org.roylance.yadel.YadelController.CommonAction(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (requestBuilder_ == null) {
          result.request_ = request_;
        } else {
          result.request_ = requestBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (responseBuilder_ == null) {
          result.response_ = response_;
        } else {
          result.response_ = responseBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.roylance.yadel.YadelController.CommonAction) {
          return mergeFrom((org.roylance.yadel.YadelController.CommonAction)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.roylance.yadel.YadelController.CommonAction other) {
        if (other == org.roylance.yadel.YadelController.CommonAction.getDefaultInstance()) return this;
        if (other.hasRequest()) {
          mergeRequest(other.getRequest());
        }
        if (other.hasResponse()) {
          mergeResponse(other.getResponse());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.roylance.yadel.YadelController.CommonAction parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.roylance.yadel.YadelController.CommonAction) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private org.roylance.yadel.YadelReport.UIRequest request_ = org.roylance.yadel.YadelReport.UIRequest.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          org.roylance.yadel.YadelReport.UIRequest, org.roylance.yadel.YadelReport.UIRequest.Builder, org.roylance.yadel.YadelReport.UIRequestOrBuilder> requestBuilder_;
      /**
       * <code>optional .org.roylance.yadel.UIRequest request = 1;</code>
       */
      public boolean hasRequest() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .org.roylance.yadel.UIRequest request = 1;</code>
       */
      public org.roylance.yadel.YadelReport.UIRequest getRequest() {
        if (requestBuilder_ == null) {
          return request_;
        } else {
          return requestBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .org.roylance.yadel.UIRequest request = 1;</code>
       */
      public Builder setRequest(org.roylance.yadel.YadelReport.UIRequest value) {
        if (requestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          request_ = value;
          onChanged();
        } else {
          requestBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .org.roylance.yadel.UIRequest request = 1;</code>
       */
      public Builder setRequest(
          org.roylance.yadel.YadelReport.UIRequest.Builder builderForValue) {
        if (requestBuilder_ == null) {
          request_ = builderForValue.build();
          onChanged();
        } else {
          requestBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .org.roylance.yadel.UIRequest request = 1;</code>
       */
      public Builder mergeRequest(org.roylance.yadel.YadelReport.UIRequest value) {
        if (requestBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              request_ != org.roylance.yadel.YadelReport.UIRequest.getDefaultInstance()) {
            request_ =
              org.roylance.yadel.YadelReport.UIRequest.newBuilder(request_).mergeFrom(value).buildPartial();
          } else {
            request_ = value;
          }
          onChanged();
        } else {
          requestBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .org.roylance.yadel.UIRequest request = 1;</code>
       */
      public Builder clearRequest() {
        if (requestBuilder_ == null) {
          request_ = org.roylance.yadel.YadelReport.UIRequest.getDefaultInstance();
          onChanged();
        } else {
          requestBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .org.roylance.yadel.UIRequest request = 1;</code>
       */
      public org.roylance.yadel.YadelReport.UIRequest.Builder getRequestBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getRequestFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .org.roylance.yadel.UIRequest request = 1;</code>
       */
      public org.roylance.yadel.YadelReport.UIRequestOrBuilder getRequestOrBuilder() {
        if (requestBuilder_ != null) {
          return requestBuilder_.getMessageOrBuilder();
        } else {
          return request_;
        }
      }
      /**
       * <code>optional .org.roylance.yadel.UIRequest request = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          org.roylance.yadel.YadelReport.UIRequest, org.roylance.yadel.YadelReport.UIRequest.Builder, org.roylance.yadel.YadelReport.UIRequestOrBuilder> 
          getRequestFieldBuilder() {
        if (requestBuilder_ == null) {
          requestBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              org.roylance.yadel.YadelReport.UIRequest, org.roylance.yadel.YadelReport.UIRequest.Builder, org.roylance.yadel.YadelReport.UIRequestOrBuilder>(
                  getRequest(),
                  getParentForChildren(),
                  isClean());
          request_ = null;
        }
        return requestBuilder_;
      }

      private org.roylance.yadel.YadelReport.UIResponse response_ = org.roylance.yadel.YadelReport.UIResponse.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          org.roylance.yadel.YadelReport.UIResponse, org.roylance.yadel.YadelReport.UIResponse.Builder, org.roylance.yadel.YadelReport.UIResponseOrBuilder> responseBuilder_;
      /**
       * <code>optional .org.roylance.yadel.UIResponse response = 2;</code>
       */
      public boolean hasResponse() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .org.roylance.yadel.UIResponse response = 2;</code>
       */
      public org.roylance.yadel.YadelReport.UIResponse getResponse() {
        if (responseBuilder_ == null) {
          return response_;
        } else {
          return responseBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .org.roylance.yadel.UIResponse response = 2;</code>
       */
      public Builder setResponse(org.roylance.yadel.YadelReport.UIResponse value) {
        if (responseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          response_ = value;
          onChanged();
        } else {
          responseBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .org.roylance.yadel.UIResponse response = 2;</code>
       */
      public Builder setResponse(
          org.roylance.yadel.YadelReport.UIResponse.Builder builderForValue) {
        if (responseBuilder_ == null) {
          response_ = builderForValue.build();
          onChanged();
        } else {
          responseBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .org.roylance.yadel.UIResponse response = 2;</code>
       */
      public Builder mergeResponse(org.roylance.yadel.YadelReport.UIResponse value) {
        if (responseBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              response_ != org.roylance.yadel.YadelReport.UIResponse.getDefaultInstance()) {
            response_ =
              org.roylance.yadel.YadelReport.UIResponse.newBuilder(response_).mergeFrom(value).buildPartial();
          } else {
            response_ = value;
          }
          onChanged();
        } else {
          responseBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .org.roylance.yadel.UIResponse response = 2;</code>
       */
      public Builder clearResponse() {
        if (responseBuilder_ == null) {
          response_ = org.roylance.yadel.YadelReport.UIResponse.getDefaultInstance();
          onChanged();
        } else {
          responseBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .org.roylance.yadel.UIResponse response = 2;</code>
       */
      public org.roylance.yadel.YadelReport.UIResponse.Builder getResponseBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getResponseFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .org.roylance.yadel.UIResponse response = 2;</code>
       */
      public org.roylance.yadel.YadelReport.UIResponseOrBuilder getResponseOrBuilder() {
        if (responseBuilder_ != null) {
          return responseBuilder_.getMessageOrBuilder();
        } else {
          return response_;
        }
      }
      /**
       * <code>optional .org.roylance.yadel.UIResponse response = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          org.roylance.yadel.YadelReport.UIResponse, org.roylance.yadel.YadelReport.UIResponse.Builder, org.roylance.yadel.YadelReport.UIResponseOrBuilder> 
          getResponseFieldBuilder() {
        if (responseBuilder_ == null) {
          responseBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              org.roylance.yadel.YadelReport.UIResponse, org.roylance.yadel.YadelReport.UIResponse.Builder, org.roylance.yadel.YadelReport.UIResponseOrBuilder>(
                  getResponse(),
                  getParentForChildren(),
                  isClean());
          response_ = null;
        }
        return responseBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:org.roylance.yadel.CommonAction)
    }

    static {
      defaultInstance = new CommonAction(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:org.roylance.yadel.CommonAction)
  }

  public interface ReportControllerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.roylance.yadel.ReportController)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .org.roylance.yadel.CommonAction delete = 1;</code>
     */
    boolean hasDelete();
    /**
     * <code>optional .org.roylance.yadel.CommonAction delete = 1;</code>
     */
    org.roylance.yadel.YadelController.CommonAction getDelete();
    /**
     * <code>optional .org.roylance.yadel.CommonAction delete = 1;</code>
     */
    org.roylance.yadel.YadelController.CommonActionOrBuilder getDeleteOrBuilder();

    /**
     * <code>optional .org.roylance.yadel.CommonAction current = 2;</code>
     */
    boolean hasCurrent();
    /**
     * <code>optional .org.roylance.yadel.CommonAction current = 2;</code>
     */
    org.roylance.yadel.YadelController.CommonAction getCurrent();
    /**
     * <code>optional .org.roylance.yadel.CommonAction current = 2;</code>
     */
    org.roylance.yadel.YadelController.CommonActionOrBuilder getCurrentOrBuilder();
  }
  /**
   * Protobuf type {@code org.roylance.yadel.ReportController}
   */
  public static final class ReportController extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:org.roylance.yadel.ReportController)
      ReportControllerOrBuilder {
    // Use ReportController.newBuilder() to construct.
    private ReportController(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ReportController(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ReportController defaultInstance;
    public static ReportController getDefaultInstance() {
      return defaultInstance;
    }

    public ReportController getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ReportController(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              org.roylance.yadel.YadelController.CommonAction.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = delete_.toBuilder();
              }
              delete_ = input.readMessage(org.roylance.yadel.YadelController.CommonAction.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(delete_);
                delete_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              org.roylance.yadel.YadelController.CommonAction.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = current_.toBuilder();
              }
              current_ = input.readMessage(org.roylance.yadel.YadelController.CommonAction.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(current_);
                current_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.roylance.yadel.YadelController.internal_static_org_roylance_yadel_ReportController_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.roylance.yadel.YadelController.internal_static_org_roylance_yadel_ReportController_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.roylance.yadel.YadelController.ReportController.class, org.roylance.yadel.YadelController.ReportController.Builder.class);
    }

    public static com.google.protobuf.Parser<ReportController> PARSER =
        new com.google.protobuf.AbstractParser<ReportController>() {
      public ReportController parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ReportController(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ReportController> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int DELETE_FIELD_NUMBER = 1;
    private org.roylance.yadel.YadelController.CommonAction delete_;
    /**
     * <code>optional .org.roylance.yadel.CommonAction delete = 1;</code>
     */
    public boolean hasDelete() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .org.roylance.yadel.CommonAction delete = 1;</code>
     */
    public org.roylance.yadel.YadelController.CommonAction getDelete() {
      return delete_;
    }
    /**
     * <code>optional .org.roylance.yadel.CommonAction delete = 1;</code>
     */
    public org.roylance.yadel.YadelController.CommonActionOrBuilder getDeleteOrBuilder() {
      return delete_;
    }

    public static final int CURRENT_FIELD_NUMBER = 2;
    private org.roylance.yadel.YadelController.CommonAction current_;
    /**
     * <code>optional .org.roylance.yadel.CommonAction current = 2;</code>
     */
    public boolean hasCurrent() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .org.roylance.yadel.CommonAction current = 2;</code>
     */
    public org.roylance.yadel.YadelController.CommonAction getCurrent() {
      return current_;
    }
    /**
     * <code>optional .org.roylance.yadel.CommonAction current = 2;</code>
     */
    public org.roylance.yadel.YadelController.CommonActionOrBuilder getCurrentOrBuilder() {
      return current_;
    }

    private void initFields() {
      delete_ = org.roylance.yadel.YadelController.CommonAction.getDefaultInstance();
      current_ = org.roylance.yadel.YadelController.CommonAction.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, delete_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, current_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, delete_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, current_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.roylance.yadel.YadelController.ReportController parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.roylance.yadel.YadelController.ReportController parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.roylance.yadel.YadelController.ReportController parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.roylance.yadel.YadelController.ReportController parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.roylance.yadel.YadelController.ReportController parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.roylance.yadel.YadelController.ReportController parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.roylance.yadel.YadelController.ReportController parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.roylance.yadel.YadelController.ReportController parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.roylance.yadel.YadelController.ReportController parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.roylance.yadel.YadelController.ReportController parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.roylance.yadel.YadelController.ReportController prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.roylance.yadel.ReportController}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.roylance.yadel.ReportController)
        org.roylance.yadel.YadelController.ReportControllerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.roylance.yadel.YadelController.internal_static_org_roylance_yadel_ReportController_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.roylance.yadel.YadelController.internal_static_org_roylance_yadel_ReportController_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.roylance.yadel.YadelController.ReportController.class, org.roylance.yadel.YadelController.ReportController.Builder.class);
      }

      // Construct using org.roylance.yadel.YadelController.ReportController.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getDeleteFieldBuilder();
          getCurrentFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (deleteBuilder_ == null) {
          delete_ = org.roylance.yadel.YadelController.CommonAction.getDefaultInstance();
        } else {
          deleteBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (currentBuilder_ == null) {
          current_ = org.roylance.yadel.YadelController.CommonAction.getDefaultInstance();
        } else {
          currentBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.roylance.yadel.YadelController.internal_static_org_roylance_yadel_ReportController_descriptor;
      }

      public org.roylance.yadel.YadelController.ReportController getDefaultInstanceForType() {
        return org.roylance.yadel.YadelController.ReportController.getDefaultInstance();
      }

      public org.roylance.yadel.YadelController.ReportController build() {
        org.roylance.yadel.YadelController.ReportController result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.roylance.yadel.YadelController.ReportController buildPartial() {
        org.roylance.yadel.YadelController.ReportController result = new org.roylance.yadel.YadelController.ReportController(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (deleteBuilder_ == null) {
          result.delete_ = delete_;
        } else {
          result.delete_ = deleteBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (currentBuilder_ == null) {
          result.current_ = current_;
        } else {
          result.current_ = currentBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.roylance.yadel.YadelController.ReportController) {
          return mergeFrom((org.roylance.yadel.YadelController.ReportController)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.roylance.yadel.YadelController.ReportController other) {
        if (other == org.roylance.yadel.YadelController.ReportController.getDefaultInstance()) return this;
        if (other.hasDelete()) {
          mergeDelete(other.getDelete());
        }
        if (other.hasCurrent()) {
          mergeCurrent(other.getCurrent());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.roylance.yadel.YadelController.ReportController parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.roylance.yadel.YadelController.ReportController) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private org.roylance.yadel.YadelController.CommonAction delete_ = org.roylance.yadel.YadelController.CommonAction.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          org.roylance.yadel.YadelController.CommonAction, org.roylance.yadel.YadelController.CommonAction.Builder, org.roylance.yadel.YadelController.CommonActionOrBuilder> deleteBuilder_;
      /**
       * <code>optional .org.roylance.yadel.CommonAction delete = 1;</code>
       */
      public boolean hasDelete() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .org.roylance.yadel.CommonAction delete = 1;</code>
       */
      public org.roylance.yadel.YadelController.CommonAction getDelete() {
        if (deleteBuilder_ == null) {
          return delete_;
        } else {
          return deleteBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .org.roylance.yadel.CommonAction delete = 1;</code>
       */
      public Builder setDelete(org.roylance.yadel.YadelController.CommonAction value) {
        if (deleteBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          delete_ = value;
          onChanged();
        } else {
          deleteBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .org.roylance.yadel.CommonAction delete = 1;</code>
       */
      public Builder setDelete(
          org.roylance.yadel.YadelController.CommonAction.Builder builderForValue) {
        if (deleteBuilder_ == null) {
          delete_ = builderForValue.build();
          onChanged();
        } else {
          deleteBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .org.roylance.yadel.CommonAction delete = 1;</code>
       */
      public Builder mergeDelete(org.roylance.yadel.YadelController.CommonAction value) {
        if (deleteBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              delete_ != org.roylance.yadel.YadelController.CommonAction.getDefaultInstance()) {
            delete_ =
              org.roylance.yadel.YadelController.CommonAction.newBuilder(delete_).mergeFrom(value).buildPartial();
          } else {
            delete_ = value;
          }
          onChanged();
        } else {
          deleteBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .org.roylance.yadel.CommonAction delete = 1;</code>
       */
      public Builder clearDelete() {
        if (deleteBuilder_ == null) {
          delete_ = org.roylance.yadel.YadelController.CommonAction.getDefaultInstance();
          onChanged();
        } else {
          deleteBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .org.roylance.yadel.CommonAction delete = 1;</code>
       */
      public org.roylance.yadel.YadelController.CommonAction.Builder getDeleteBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getDeleteFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .org.roylance.yadel.CommonAction delete = 1;</code>
       */
      public org.roylance.yadel.YadelController.CommonActionOrBuilder getDeleteOrBuilder() {
        if (deleteBuilder_ != null) {
          return deleteBuilder_.getMessageOrBuilder();
        } else {
          return delete_;
        }
      }
      /**
       * <code>optional .org.roylance.yadel.CommonAction delete = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          org.roylance.yadel.YadelController.CommonAction, org.roylance.yadel.YadelController.CommonAction.Builder, org.roylance.yadel.YadelController.CommonActionOrBuilder> 
          getDeleteFieldBuilder() {
        if (deleteBuilder_ == null) {
          deleteBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              org.roylance.yadel.YadelController.CommonAction, org.roylance.yadel.YadelController.CommonAction.Builder, org.roylance.yadel.YadelController.CommonActionOrBuilder>(
                  getDelete(),
                  getParentForChildren(),
                  isClean());
          delete_ = null;
        }
        return deleteBuilder_;
      }

      private org.roylance.yadel.YadelController.CommonAction current_ = org.roylance.yadel.YadelController.CommonAction.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          org.roylance.yadel.YadelController.CommonAction, org.roylance.yadel.YadelController.CommonAction.Builder, org.roylance.yadel.YadelController.CommonActionOrBuilder> currentBuilder_;
      /**
       * <code>optional .org.roylance.yadel.CommonAction current = 2;</code>
       */
      public boolean hasCurrent() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .org.roylance.yadel.CommonAction current = 2;</code>
       */
      public org.roylance.yadel.YadelController.CommonAction getCurrent() {
        if (currentBuilder_ == null) {
          return current_;
        } else {
          return currentBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .org.roylance.yadel.CommonAction current = 2;</code>
       */
      public Builder setCurrent(org.roylance.yadel.YadelController.CommonAction value) {
        if (currentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          current_ = value;
          onChanged();
        } else {
          currentBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .org.roylance.yadel.CommonAction current = 2;</code>
       */
      public Builder setCurrent(
          org.roylance.yadel.YadelController.CommonAction.Builder builderForValue) {
        if (currentBuilder_ == null) {
          current_ = builderForValue.build();
          onChanged();
        } else {
          currentBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .org.roylance.yadel.CommonAction current = 2;</code>
       */
      public Builder mergeCurrent(org.roylance.yadel.YadelController.CommonAction value) {
        if (currentBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              current_ != org.roylance.yadel.YadelController.CommonAction.getDefaultInstance()) {
            current_ =
              org.roylance.yadel.YadelController.CommonAction.newBuilder(current_).mergeFrom(value).buildPartial();
          } else {
            current_ = value;
          }
          onChanged();
        } else {
          currentBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .org.roylance.yadel.CommonAction current = 2;</code>
       */
      public Builder clearCurrent() {
        if (currentBuilder_ == null) {
          current_ = org.roylance.yadel.YadelController.CommonAction.getDefaultInstance();
          onChanged();
        } else {
          currentBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .org.roylance.yadel.CommonAction current = 2;</code>
       */
      public org.roylance.yadel.YadelController.CommonAction.Builder getCurrentBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getCurrentFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .org.roylance.yadel.CommonAction current = 2;</code>
       */
      public org.roylance.yadel.YadelController.CommonActionOrBuilder getCurrentOrBuilder() {
        if (currentBuilder_ != null) {
          return currentBuilder_.getMessageOrBuilder();
        } else {
          return current_;
        }
      }
      /**
       * <code>optional .org.roylance.yadel.CommonAction current = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          org.roylance.yadel.YadelController.CommonAction, org.roylance.yadel.YadelController.CommonAction.Builder, org.roylance.yadel.YadelController.CommonActionOrBuilder> 
          getCurrentFieldBuilder() {
        if (currentBuilder_ == null) {
          currentBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              org.roylance.yadel.YadelController.CommonAction, org.roylance.yadel.YadelController.CommonAction.Builder, org.roylance.yadel.YadelController.CommonActionOrBuilder>(
                  getCurrent(),
                  getParentForChildren(),
                  isClean());
          current_ = null;
        }
        return currentBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:org.roylance.yadel.ReportController)
    }

    static {
      defaultInstance = new ReportController(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:org.roylance.yadel.ReportController)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_roylance_yadel_CommonAction_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_roylance_yadel_CommonAction_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_roylance_yadel_ReportController_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_roylance_yadel_ReportController_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026yadel_controller.proto\022\022org.roylance.y" +
      "adel\032\022yadel_report.proto\"p\n\014CommonAction" +
      "\022.\n\007request\030\001 \001(\0132\035.org.roylance.yadel.U" +
      "IRequest\0220\n\010response\030\002 \001(\0132\036.org.roylanc" +
      "e.yadel.UIResponse\"w\n\020ReportController\0220" +
      "\n\006delete\030\001 \001(\0132 .org.roylance.yadel.Comm" +
      "onAction\0221\n\007current\030\002 \001(\0132 .org.roylance" +
      ".yadel.CommonAction"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.roylance.yadel.YadelReport.getDescriptor(),
        }, assigner);
    internal_static_org_roylance_yadel_CommonAction_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_roylance_yadel_CommonAction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_roylance_yadel_CommonAction_descriptor,
        new java.lang.String[] { "Request", "Response", });
    internal_static_org_roylance_yadel_ReportController_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_roylance_yadel_ReportController_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_roylance_yadel_ReportController_descriptor,
        new java.lang.String[] { "Delete", "Current", });
    org.roylance.yadel.YadelReport.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
