/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_roylance_yadel_services_ReportJNIBridge */

#ifndef _Included_org_roylance_yadel_services_ReportJNIBridge
#define _Included_org_roylance_yadel_services_ReportJNIBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_roylance_yadel_services_ReportJNIBridge
 * Method:    delete_dagJNI
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_roylance_yadel_services_ReportJNIBridge_delete_1dagJNI
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     org_roylance_yadel_services_ReportJNIBridge
 * Method:    currentJNI
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_roylance_yadel_services_ReportJNIBridge_currentJNI
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     org_roylance_yadel_services_ReportJNIBridge
 * Method:    get_dag_statusJNI
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_roylance_yadel_services_ReportJNIBridge_get_1dag_1statusJNI
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
