/*
 * DO NOT EDIT.
 *
 * Generated by the protocol buffer compiler.
 * Source: yadel_model.proto
 *
 */

import Foundation
import SwiftProtobuf


public enum Org_Roylance_Yadel_OSBitVersion: SwiftProtobuf.Enum {
  public typealias RawValue = Int
  case v64BitVersion // = 0
  case v32BitVersion // = 1
  case UNRECOGNIZED(Int)

  public init() {
    self = .v64BitVersion
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .v64BitVersion
    case 1: self = .v32BitVersion
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public init?(name: String) {
    switch name {
    case "v64BitVersion": self = .v64BitVersion
    case "v32BitVersion": self = .v32BitVersion
    default: return nil
    }
  }

  public init?(jsonName: String) {
    switch jsonName {
    case "V_64_BIT_VERSION": self = .v64BitVersion
    case "V_32_BIT_VERSION": self = .v32BitVersion
    default: return nil
    }
  }

  public init?(protoName: String) {
    switch protoName {
    case "V_64_BIT_VERSION": self = .v64BitVersion
    case "V_32_BIT_VERSION": self = .v32BitVersion
    default: return nil
    }
  }

  public var rawValue: Int {
    get {
      switch self {
      case .v64BitVersion: return 0
      case .v32BitVersion: return 1
      case .UNRECOGNIZED(let i): return i
      }
    }
  }

  public var json: String {
    get {
      switch self {
      case .v64BitVersion: return "\"V_64_BIT_VERSION\""
      case .v32BitVersion: return "\"V_32_BIT_VERSION\""
      case .UNRECOGNIZED(let i): return String(i)
      }
    }
  }

  public var hashValue: Int { return rawValue }

  public var debugDescription: String {
    get {
      switch self {
      case .v64BitVersion: return ".v64BitVersion"
      case .v32BitVersion: return ".v32BitVersion"
      case .UNRECOGNIZED(let v): return ".UNRECOGNIZED(\(v))"
      }
    }
  }

}

public enum Org_Roylance_Yadel_OSTypeVersion: SwiftProtobuf.Enum {
  public typealias RawValue = Int
  case macOsTypeVersion // = 0
  case winOsTypeVersion // = 1
  case ubuntuOsTypeVersion // = 2
  case centosOsTypeVersion // = 3
  case fedoraOsTypeVersion // = 4
  case redhatOsTypeVersion // = 5
  case linuxOsTypeVersion // = 6
  case UNRECOGNIZED(Int)

  public init() {
    self = .macOsTypeVersion
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .macOsTypeVersion
    case 1: self = .winOsTypeVersion
    case 2: self = .ubuntuOsTypeVersion
    case 3: self = .centosOsTypeVersion
    case 4: self = .fedoraOsTypeVersion
    case 5: self = .redhatOsTypeVersion
    case 6: self = .linuxOsTypeVersion
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public init?(name: String) {
    switch name {
    case "macOsTypeVersion": self = .macOsTypeVersion
    case "winOsTypeVersion": self = .winOsTypeVersion
    case "ubuntuOsTypeVersion": self = .ubuntuOsTypeVersion
    case "centosOsTypeVersion": self = .centosOsTypeVersion
    case "fedoraOsTypeVersion": self = .fedoraOsTypeVersion
    case "redhatOsTypeVersion": self = .redhatOsTypeVersion
    case "linuxOsTypeVersion": self = .linuxOsTypeVersion
    default: return nil
    }
  }

  public init?(jsonName: String) {
    switch jsonName {
    case "MAC_OS_TYPE_VERSION": self = .macOsTypeVersion
    case "WIN_OS_TYPE_VERSION": self = .winOsTypeVersion
    case "UBUNTU_OS_TYPE_VERSION": self = .ubuntuOsTypeVersion
    case "CENTOS_OS_TYPE_VERSION": self = .centosOsTypeVersion
    case "FEDORA_OS_TYPE_VERSION": self = .fedoraOsTypeVersion
    case "REDHAT_OS_TYPE_VERSION": self = .redhatOsTypeVersion
    case "LINUX_OS_TYPE_VERSION": self = .linuxOsTypeVersion
    default: return nil
    }
  }

  public init?(protoName: String) {
    switch protoName {
    case "MAC_OS_TYPE_VERSION": self = .macOsTypeVersion
    case "WIN_OS_TYPE_VERSION": self = .winOsTypeVersion
    case "UBUNTU_OS_TYPE_VERSION": self = .ubuntuOsTypeVersion
    case "CENTOS_OS_TYPE_VERSION": self = .centosOsTypeVersion
    case "FEDORA_OS_TYPE_VERSION": self = .fedoraOsTypeVersion
    case "REDHAT_OS_TYPE_VERSION": self = .redhatOsTypeVersion
    case "LINUX_OS_TYPE_VERSION": self = .linuxOsTypeVersion
    default: return nil
    }
  }

  public var rawValue: Int {
    get {
      switch self {
      case .macOsTypeVersion: return 0
      case .winOsTypeVersion: return 1
      case .ubuntuOsTypeVersion: return 2
      case .centosOsTypeVersion: return 3
      case .fedoraOsTypeVersion: return 4
      case .redhatOsTypeVersion: return 5
      case .linuxOsTypeVersion: return 6
      case .UNRECOGNIZED(let i): return i
      }
    }
  }

  public var json: String {
    get {
      switch self {
      case .macOsTypeVersion: return "\"MAC_OS_TYPE_VERSION\""
      case .winOsTypeVersion: return "\"WIN_OS_TYPE_VERSION\""
      case .ubuntuOsTypeVersion: return "\"UBUNTU_OS_TYPE_VERSION\""
      case .centosOsTypeVersion: return "\"CENTOS_OS_TYPE_VERSION\""
      case .fedoraOsTypeVersion: return "\"FEDORA_OS_TYPE_VERSION\""
      case .redhatOsTypeVersion: return "\"REDHAT_OS_TYPE_VERSION\""
      case .linuxOsTypeVersion: return "\"LINUX_OS_TYPE_VERSION\""
      case .UNRECOGNIZED(let i): return String(i)
      }
    }
  }

  public var hashValue: Int { return rawValue }

  public var debugDescription: String {
    get {
      switch self {
      case .macOsTypeVersion: return ".macOsTypeVersion"
      case .winOsTypeVersion: return ".winOsTypeVersion"
      case .ubuntuOsTypeVersion: return ".ubuntuOsTypeVersion"
      case .centosOsTypeVersion: return ".centosOsTypeVersion"
      case .fedoraOsTypeVersion: return ".fedoraOsTypeVersion"
      case .redhatOsTypeVersion: return ".redhatOsTypeVersion"
      case .linuxOsTypeVersion: return ".linuxOsTypeVersion"
      case .UNRECOGNIZED(let v): return ".UNRECOGNIZED(\(v))"
      }
    }
  }

}

public enum Org_Roylance_Yadel_WorkerState: SwiftProtobuf.Enum {
  public typealias RawValue = Int
  case working // = 0
  case idle // = 1
  case UNRECOGNIZED(Int)

  public init() {
    self = .working
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .working
    case 1: self = .idle
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public init?(name: String) {
    switch name {
    case "working": self = .working
    case "idle": self = .idle
    default: return nil
    }
  }

  public init?(jsonName: String) {
    switch jsonName {
    case "WORKING": self = .working
    case "IDLE": self = .idle
    default: return nil
    }
  }

  public init?(protoName: String) {
    switch protoName {
    case "WORKING": self = .working
    case "IDLE": self = .idle
    default: return nil
    }
  }

  public var rawValue: Int {
    get {
      switch self {
      case .working: return 0
      case .idle: return 1
      case .UNRECOGNIZED(let i): return i
      }
    }
  }

  public var json: String {
    get {
      switch self {
      case .working: return "\"WORKING\""
      case .idle: return "\"IDLE\""
      case .UNRECOGNIZED(let i): return String(i)
      }
    }
  }

  public var hashValue: Int { return rawValue }

  public var debugDescription: String {
    get {
      switch self {
      case .working: return ".working"
      case .idle: return ".idle"
      case .UNRECOGNIZED(let v): return ".UNRECOGNIZED(\(v))"
      }
    }
  }

}

public enum Org_Roylance_Yadel_WorkerToManagerMessageType: SwiftProtobuf.Enum {
  public typealias RawValue = Int
  case registration // = 0
  case UNRECOGNIZED(Int)

  public init() {
    self = .registration
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .registration
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public init?(name: String) {
    switch name {
    case "registration": self = .registration
    default: return nil
    }
  }

  public init?(jsonName: String) {
    switch jsonName {
    case "REGISTRATION": self = .registration
    default: return nil
    }
  }

  public init?(protoName: String) {
    switch protoName {
    case "REGISTRATION": self = .registration
    default: return nil
    }
  }

  public var rawValue: Int {
    get {
      switch self {
      case .registration: return 0
      case .UNRECOGNIZED(let i): return i
      }
    }
  }

  public var json: String {
    get {
      switch self {
      case .registration: return "\"REGISTRATION\""
      case .UNRECOGNIZED(let i): return String(i)
      }
    }
  }

  public var hashValue: Int { return rawValue }

  public var debugDescription: String {
    get {
      switch self {
      case .registration: return ".registration"
      case .UNRECOGNIZED(let v): return ".UNRECOGNIZED(\(v))"
      }
    }
  }

}

public enum Org_Roylance_Yadel_ManagerToManagerMessageType: SwiftProtobuf.Enum {
  public typealias RawValue = Int
  case ensureWorkersWorking // = 0
  case UNRECOGNIZED(Int)

  public init() {
    self = .ensureWorkersWorking
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .ensureWorkersWorking
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public init?(name: String) {
    switch name {
    case "ensureWorkersWorking": self = .ensureWorkersWorking
    default: return nil
    }
  }

  public init?(jsonName: String) {
    switch jsonName {
    case "ENSURE_WORKERS_WORKING": self = .ensureWorkersWorking
    default: return nil
    }
  }

  public init?(protoName: String) {
    switch protoName {
    case "ENSURE_WORKERS_WORKING": self = .ensureWorkersWorking
    default: return nil
    }
  }

  public var rawValue: Int {
    get {
      switch self {
      case .ensureWorkersWorking: return 0
      case .UNRECOGNIZED(let i): return i
      }
    }
  }

  public var json: String {
    get {
      switch self {
      case .ensureWorkersWorking: return "\"ENSURE_WORKERS_WORKING\""
      case .UNRECOGNIZED(let i): return String(i)
      }
    }
  }

  public var hashValue: Int { return rawValue }

  public var debugDescription: String {
    get {
      switch self {
      case .ensureWorkersWorking: return ".ensureWorkersWorking"
      case .UNRECOGNIZED(let v): return ".UNRECOGNIZED(\(v))"
      }
    }
  }

}

public enum Org_Roylance_Yadel_ActorRole: SwiftProtobuf.Enum {
  public typealias RawValue = Int
  case manager // = 0
  case worker // = 1
  case UNRECOGNIZED(Int)

  public init() {
    self = .manager
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .manager
    case 1: self = .worker
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public init?(name: String) {
    switch name {
    case "manager": self = .manager
    case "worker": self = .worker
    default: return nil
    }
  }

  public init?(jsonName: String) {
    switch jsonName {
    case "MANAGER": self = .manager
    case "WORKER": self = .worker
    default: return nil
    }
  }

  public init?(protoName: String) {
    switch protoName {
    case "MANAGER": self = .manager
    case "WORKER": self = .worker
    default: return nil
    }
  }

  public var rawValue: Int {
    get {
      switch self {
      case .manager: return 0
      case .worker: return 1
      case .UNRECOGNIZED(let i): return i
      }
    }
  }

  public var json: String {
    get {
      switch self {
      case .manager: return "\"MANAGER\""
      case .worker: return "\"WORKER\""
      case .UNRECOGNIZED(let i): return String(i)
      }
    }
  }

  public var hashValue: Int { return rawValue }

  public var debugDescription: String {
    get {
      switch self {
      case .manager: return ".manager"
      case .worker: return ".worker"
      case .UNRECOGNIZED(let v): return ".UNRECOGNIZED(\(v))"
      }
    }
  }

}

public enum Org_Roylance_Yadel_WorkerOperationsComparison: SwiftProtobuf.Enum {
  public typealias RawValue = Int
  case equalsOperation // = 0
  case notEqualsOperation // = 1
  case greaterThanOperation // = 2
  case lessThanOperation // = 3
  case greaterThanOrEqualsOperation // = 4
  case lessThanOrEqualsOperation // = 5
  case containsOperation // = 6
  case matchesOperation // = 7
  case UNRECOGNIZED(Int)

  public init() {
    self = .equalsOperation
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .equalsOperation
    case 1: self = .notEqualsOperation
    case 2: self = .greaterThanOperation
    case 3: self = .lessThanOperation
    case 4: self = .greaterThanOrEqualsOperation
    case 5: self = .lessThanOrEqualsOperation
    case 6: self = .containsOperation
    case 7: self = .matchesOperation
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public init?(name: String) {
    switch name {
    case "equalsOperation": self = .equalsOperation
    case "notEqualsOperation": self = .notEqualsOperation
    case "greaterThanOperation": self = .greaterThanOperation
    case "lessThanOperation": self = .lessThanOperation
    case "greaterThanOrEqualsOperation": self = .greaterThanOrEqualsOperation
    case "lessThanOrEqualsOperation": self = .lessThanOrEqualsOperation
    case "containsOperation": self = .containsOperation
    case "matchesOperation": self = .matchesOperation
    default: return nil
    }
  }

  public init?(jsonName: String) {
    switch jsonName {
    case "EQUALS_OPERATION": self = .equalsOperation
    case "NOT_EQUALS_OPERATION": self = .notEqualsOperation
    case "GREATER_THAN_OPERATION": self = .greaterThanOperation
    case "LESS_THAN_OPERATION": self = .lessThanOperation
    case "GREATER_THAN_OR_EQUALS_OPERATION": self = .greaterThanOrEqualsOperation
    case "LESS_THAN_OR_EQUALS_OPERATION": self = .lessThanOrEqualsOperation
    case "CONTAINS_OPERATION": self = .containsOperation
    case "MATCHES_OPERATION": self = .matchesOperation
    default: return nil
    }
  }

  public init?(protoName: String) {
    switch protoName {
    case "EQUALS_OPERATION": self = .equalsOperation
    case "NOT_EQUALS_OPERATION": self = .notEqualsOperation
    case "GREATER_THAN_OPERATION": self = .greaterThanOperation
    case "LESS_THAN_OPERATION": self = .lessThanOperation
    case "GREATER_THAN_OR_EQUALS_OPERATION": self = .greaterThanOrEqualsOperation
    case "LESS_THAN_OR_EQUALS_OPERATION": self = .lessThanOrEqualsOperation
    case "CONTAINS_OPERATION": self = .containsOperation
    case "MATCHES_OPERATION": self = .matchesOperation
    default: return nil
    }
  }

  public var rawValue: Int {
    get {
      switch self {
      case .equalsOperation: return 0
      case .notEqualsOperation: return 1
      case .greaterThanOperation: return 2
      case .lessThanOperation: return 3
      case .greaterThanOrEqualsOperation: return 4
      case .lessThanOrEqualsOperation: return 5
      case .containsOperation: return 6
      case .matchesOperation: return 7
      case .UNRECOGNIZED(let i): return i
      }
    }
  }

  public var json: String {
    get {
      switch self {
      case .equalsOperation: return "\"EQUALS_OPERATION\""
      case .notEqualsOperation: return "\"NOT_EQUALS_OPERATION\""
      case .greaterThanOperation: return "\"GREATER_THAN_OPERATION\""
      case .lessThanOperation: return "\"LESS_THAN_OPERATION\""
      case .greaterThanOrEqualsOperation: return "\"GREATER_THAN_OR_EQUALS_OPERATION\""
      case .lessThanOrEqualsOperation: return "\"LESS_THAN_OR_EQUALS_OPERATION\""
      case .containsOperation: return "\"CONTAINS_OPERATION\""
      case .matchesOperation: return "\"MATCHES_OPERATION\""
      case .UNRECOGNIZED(let i): return String(i)
      }
    }
  }

  public var hashValue: Int { return rawValue }

  public var debugDescription: String {
    get {
      switch self {
      case .equalsOperation: return ".equalsOperation"
      case .notEqualsOperation: return ".notEqualsOperation"
      case .greaterThanOperation: return ".greaterThanOperation"
      case .lessThanOperation: return ".lessThanOperation"
      case .greaterThanOrEqualsOperation: return ".greaterThanOrEqualsOperation"
      case .lessThanOrEqualsOperation: return ".lessThanOrEqualsOperation"
      case .containsOperation: return ".containsOperation"
      case .matchesOperation: return ".matchesOperation"
      case .UNRECOGNIZED(let v): return ".UNRECOGNIZED(\(v))"
      }
    }
  }

}

public enum Org_Roylance_Yadel_WorkerConnection: SwiftProtobuf.Enum {
  public typealias RawValue = Int
  case none // = 0
  case and // = 1
  case or // = 2
  case UNRECOGNIZED(Int)

  public init() {
    self = .none
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .none
    case 1: self = .and
    case 2: self = .or
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public init?(name: String) {
    switch name {
    case "none": self = .none
    case "and": self = .and
    case "or": self = .or
    default: return nil
    }
  }

  public init?(jsonName: String) {
    switch jsonName {
    case "NONE": self = .none
    case "AND": self = .and
    case "OR": self = .or
    default: return nil
    }
  }

  public init?(protoName: String) {
    switch protoName {
    case "NONE": self = .none
    case "AND": self = .and
    case "OR": self = .or
    default: return nil
    }
  }

  public var rawValue: Int {
    get {
      switch self {
      case .none: return 0
      case .and: return 1
      case .or: return 2
      case .UNRECOGNIZED(let i): return i
      }
    }
  }

  public var json: String {
    get {
      switch self {
      case .none: return "\"NONE\""
      case .and: return "\"AND\""
      case .or: return "\"OR\""
      case .UNRECOGNIZED(let i): return String(i)
      }
    }
  }

  public var hashValue: Int { return rawValue }

  public var debugDescription: String {
    get {
      switch self {
      case .none: return ".none"
      case .and: return ".and"
      case .or: return ".or"
      case .UNRECOGNIZED(let v): return ".UNRECOGNIZED(\(v))"
      }
    }
  }

}

public struct Org_Roylance_Yadel_WorkerProperty: SwiftProtobuf.Message, SwiftProtobuf.Proto3Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf.ProtoNameProviding {
  public var swiftClassName: String {return "Org_Roylance_Yadel_WorkerProperty"}
  public var protoMessageName: String {return "WorkerProperty"}
  public var protoPackageName: String {return "org.roylance.yadel"}
  public static let _protobuf_fieldNames: FieldNameMap = [
    1: .same(proto: "id", swift: "id"),
    2: .same(proto: "key", swift: "key"),
    3: .same(proto: "value", swift: "value"),
    4: .unique(proto: "number_value", json: "numberValue", swift: "numberValue"),
    5: .unique(proto: "os_bit_version", json: "osBitVersion", swift: "osBitVersion"),
    6: .unique(proto: "os_type_version", json: "osTypeVersion", swift: "osTypeVersion"),
  ]


  public var id: String = ""

  public var key: String = ""

  public var value: String = ""

  public var numberValue: Double = 0

  public var osBitVersion: Org_Roylance_Yadel_OSBitVersion = Org_Roylance_Yadel_OSBitVersion.v64BitVersion

  public var osTypeVersion: Org_Roylance_Yadel_OSTypeVersion = Org_Roylance_Yadel_OSTypeVersion.macOsTypeVersion

  public init() {}

  public mutating func _protoc_generated_decodeField<T: SwiftProtobuf.FieldDecoder>(setter: inout T, protoFieldNumber: Int) throws {
    switch protoFieldNumber {
    case 1: try setter.decodeSingularField(fieldType: SwiftProtobuf.ProtobufString.self, value: &id)
    case 2: try setter.decodeSingularField(fieldType: SwiftProtobuf.ProtobufString.self, value: &key)
    case 3: try setter.decodeSingularField(fieldType: SwiftProtobuf.ProtobufString.self, value: &value)
    case 4: try setter.decodeSingularField(fieldType: SwiftProtobuf.ProtobufDouble.self, value: &numberValue)
    case 5: try setter.decodeSingularField(fieldType: Org_Roylance_Yadel_OSBitVersion.self, value: &osBitVersion)
    case 6: try setter.decodeSingularField(fieldType: Org_Roylance_Yadel_OSTypeVersion.self, value: &osTypeVersion)
    default: break
    }
  }

  public func _protoc_generated_traverse(visitor: SwiftProtobuf.Visitor) throws {
    if id != "" {
      try visitor.visitSingularField(fieldType: SwiftProtobuf.ProtobufString.self, value: id, fieldNumber: 1)
    }
    if key != "" {
      try visitor.visitSingularField(fieldType: SwiftProtobuf.ProtobufString.self, value: key, fieldNumber: 2)
    }
    if value != "" {
      try visitor.visitSingularField(fieldType: SwiftProtobuf.ProtobufString.self, value: value, fieldNumber: 3)
    }
    if numberValue != 0 {
      try visitor.visitSingularField(fieldType: SwiftProtobuf.ProtobufDouble.self, value: numberValue, fieldNumber: 4)
    }
    if osBitVersion != Org_Roylance_Yadel_OSBitVersion.v64BitVersion {
      try visitor.visitSingularField(fieldType: Org_Roylance_Yadel_OSBitVersion.self, value: osBitVersion, fieldNumber: 5)
    }
    if osTypeVersion != Org_Roylance_Yadel_OSTypeVersion.macOsTypeVersion {
      try visitor.visitSingularField(fieldType: Org_Roylance_Yadel_OSTypeVersion.self, value: osTypeVersion, fieldNumber: 6)
    }
  }

  public func _protoc_generated_isEqualTo(other: Org_Roylance_Yadel_WorkerProperty) -> Bool {
    if id != other.id {return false}
    if key != other.key {return false}
    if value != other.value {return false}
    if numberValue != other.numberValue {return false}
    if osBitVersion != other.osBitVersion {return false}
    if osTypeVersion != other.osTypeVersion {return false}
    return true
  }
}

public struct Org_Roylance_Yadel_WorkerFilter: SwiftProtobuf.Message, SwiftProtobuf.Proto3Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf.ProtoNameProviding {
  public var swiftClassName: String {return "Org_Roylance_Yadel_WorkerFilter"}
  public var protoMessageName: String {return "WorkerFilter"}
  public var protoPackageName: String {return "org.roylance.yadel"}
  public static let _protobuf_fieldNames: FieldNameMap = [
    1: .same(proto: "id", swift: "id"),
    2: .unique(proto: "first_property", json: "firstProperty", swift: "firstProperty"),
    3: .unique(proto: "first_comparison", json: "firstComparison", swift: "firstComparison"),
    4: .unique(proto: "second_property", json: "secondProperty", swift: "secondProperty"),
    5: .unique(proto: "second_comparison", json: "secondComparison", swift: "secondComparison"),
    6: .same(proto: "operation", swift: "operation"),
    7: .same(proto: "connection", swift: "connection"),
    8: .unique(proto: "first_operator", json: "firstOperator", swift: "firstOperator"),
    9: .unique(proto: "second_operator", json: "secondOperator", swift: "secondOperator"),
  ]

  private class _StorageClass {
    typealias ExtendedMessage = Org_Roylance_Yadel_WorkerFilter
    var _id: String = ""
    var _firstProperty: Org_Roylance_Yadel_WorkerProperty? = nil
    var _firstComparison: Org_Roylance_Yadel_WorkerFilter? = nil
    var _secondProperty: Org_Roylance_Yadel_WorkerProperty? = nil
    var _secondComparison: Org_Roylance_Yadel_WorkerFilter? = nil
    var _operation: Org_Roylance_Yadel_WorkerOperationsComparison = Org_Roylance_Yadel_WorkerOperationsComparison.equalsOperation
    var _connection: Org_Roylance_Yadel_WorkerConnection = Org_Roylance_Yadel_WorkerConnection.none
    var _firstOperator: Org_Roylance_Yadel_WorkerOperationsComparison = Org_Roylance_Yadel_WorkerOperationsComparison.equalsOperation
    var _secondOperator: Org_Roylance_Yadel_WorkerOperationsComparison = Org_Roylance_Yadel_WorkerOperationsComparison.equalsOperation

    init() {}

    func decodeField<T: SwiftProtobuf.FieldDecoder>(setter: inout T, protoFieldNumber: Int) throws {
      switch protoFieldNumber {
      case 1: try setter.decodeSingularField(fieldType: SwiftProtobuf.ProtobufString.self, value: &_id)
      case 2: try setter.decodeSingularMessageField(fieldType: Org_Roylance_Yadel_WorkerProperty.self, value: &_firstProperty)
      case 3: try setter.decodeSingularMessageField(fieldType: Org_Roylance_Yadel_WorkerFilter.self, value: &_firstComparison)
      case 4: try setter.decodeSingularMessageField(fieldType: Org_Roylance_Yadel_WorkerProperty.self, value: &_secondProperty)
      case 5: try setter.decodeSingularMessageField(fieldType: Org_Roylance_Yadel_WorkerFilter.self, value: &_secondComparison)
      case 6: try setter.decodeSingularField(fieldType: Org_Roylance_Yadel_WorkerOperationsComparison.self, value: &_operation)
      case 7: try setter.decodeSingularField(fieldType: Org_Roylance_Yadel_WorkerConnection.self, value: &_connection)
      case 8: try setter.decodeSingularField(fieldType: Org_Roylance_Yadel_WorkerOperationsComparison.self, value: &_firstOperator)
      case 9: try setter.decodeSingularField(fieldType: Org_Roylance_Yadel_WorkerOperationsComparison.self, value: &_secondOperator)
      default: break
      }
    }

    func traverse(visitor: SwiftProtobuf.Visitor) throws {
      if _id != "" {
        try visitor.visitSingularField(fieldType: SwiftProtobuf.ProtobufString.self, value: _id, fieldNumber: 1)
      }
      if let v = _firstProperty {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
      }
      if let v = _firstComparison {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
      }
      if let v = _secondProperty {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
      }
      if let v = _secondComparison {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
      }
      if _operation != Org_Roylance_Yadel_WorkerOperationsComparison.equalsOperation {
        try visitor.visitSingularField(fieldType: Org_Roylance_Yadel_WorkerOperationsComparison.self, value: _operation, fieldNumber: 6)
      }
      if _connection != Org_Roylance_Yadel_WorkerConnection.none {
        try visitor.visitSingularField(fieldType: Org_Roylance_Yadel_WorkerConnection.self, value: _connection, fieldNumber: 7)
      }
      if _firstOperator != Org_Roylance_Yadel_WorkerOperationsComparison.equalsOperation {
        try visitor.visitSingularField(fieldType: Org_Roylance_Yadel_WorkerOperationsComparison.self, value: _firstOperator, fieldNumber: 8)
      }
      if _secondOperator != Org_Roylance_Yadel_WorkerOperationsComparison.equalsOperation {
        try visitor.visitSingularField(fieldType: Org_Roylance_Yadel_WorkerOperationsComparison.self, value: _secondOperator, fieldNumber: 9)
      }
    }

    func isEqualTo(other: _StorageClass) -> Bool {
      if _id != other._id {return false}
      if _firstProperty != other._firstProperty {return false}
      if _firstComparison != other._firstComparison {return false}
      if _secondProperty != other._secondProperty {return false}
      if _secondComparison != other._secondComparison {return false}
      if _operation != other._operation {return false}
      if _connection != other._connection {return false}
      if _firstOperator != other._firstOperator {return false}
      if _secondOperator != other._secondOperator {return false}
      return true
    }

    func copy() -> _StorageClass {
      let clone = _StorageClass()
      clone._id = _id
      clone._firstProperty = _firstProperty
      clone._firstComparison = _firstComparison
      clone._secondProperty = _secondProperty
      clone._secondComparison = _secondComparison
      clone._operation = _operation
      clone._connection = _connection
      clone._firstOperator = _firstOperator
      clone._secondOperator = _secondOperator
      return clone
    }
  }

  private var _storage = _StorageClass()


  public var id: String {
    get {return _storage._id}
    set {_uniqueStorage()._id = newValue}
  }

  public var firstProperty: Org_Roylance_Yadel_WorkerProperty {
    get {return _storage._firstProperty ?? Org_Roylance_Yadel_WorkerProperty()}
    set {_uniqueStorage()._firstProperty = newValue}
  }
  public var hasFirstProperty: Bool {
    return _storage._firstProperty != nil
  }
  public mutating func clearFirstProperty() {
    return _storage._firstProperty = nil
  }

  public var firstComparison: Org_Roylance_Yadel_WorkerFilter {
    get {return _storage._firstComparison ?? Org_Roylance_Yadel_WorkerFilter()}
    set {_uniqueStorage()._firstComparison = newValue}
  }
  public var hasFirstComparison: Bool {
    return _storage._firstComparison != nil
  }
  public mutating func clearFirstComparison() {
    return _storage._firstComparison = nil
  }

  public var secondProperty: Org_Roylance_Yadel_WorkerProperty {
    get {return _storage._secondProperty ?? Org_Roylance_Yadel_WorkerProperty()}
    set {_uniqueStorage()._secondProperty = newValue}
  }
  public var hasSecondProperty: Bool {
    return _storage._secondProperty != nil
  }
  public mutating func clearSecondProperty() {
    return _storage._secondProperty = nil
  }

  public var secondComparison: Org_Roylance_Yadel_WorkerFilter {
    get {return _storage._secondComparison ?? Org_Roylance_Yadel_WorkerFilter()}
    set {_uniqueStorage()._secondComparison = newValue}
  }
  public var hasSecondComparison: Bool {
    return _storage._secondComparison != nil
  }
  public mutating func clearSecondComparison() {
    return _storage._secondComparison = nil
  }

  public var operation: Org_Roylance_Yadel_WorkerOperationsComparison {
    get {return _storage._operation}
    set {_uniqueStorage()._operation = newValue}
  }

  public var connection: Org_Roylance_Yadel_WorkerConnection {
    get {return _storage._connection}
    set {_uniqueStorage()._connection = newValue}
  }

  public var firstOperator: Org_Roylance_Yadel_WorkerOperationsComparison {
    get {return _storage._firstOperator}
    set {_uniqueStorage()._firstOperator = newValue}
  }

  public var secondOperator: Org_Roylance_Yadel_WorkerOperationsComparison {
    get {return _storage._secondOperator}
    set {_uniqueStorage()._secondOperator = newValue}
  }

  public init() {}

  public mutating func _protoc_generated_decodeField<T: SwiftProtobuf.FieldDecoder>(setter: inout T, protoFieldNumber: Int) throws {
    try _uniqueStorage().decodeField(setter: &setter, protoFieldNumber: protoFieldNumber)
  }

  public func _protoc_generated_traverse(visitor: SwiftProtobuf.Visitor) throws {
    try _storage.traverse(visitor: visitor)
  }

  public func _protoc_generated_isEqualTo(other: Org_Roylance_Yadel_WorkerFilter) -> Bool {
    return _storage === other._storage || _storage.isEqualTo(other: other._storage)
  }

  private mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _storage.copy()
    }
    return _storage
  }
}

public struct Org_Roylance_Yadel_WorkerConfiguration: SwiftProtobuf.Message, SwiftProtobuf.Proto3Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf.ProtoNameProviding {
  public var swiftClassName: String {return "Org_Roylance_Yadel_WorkerConfiguration"}
  public var protoMessageName: String {return "WorkerConfiguration"}
  public var protoPackageName: String {return "org.roylance.yadel"}
  public static let _protobuf_fieldNames: FieldNameMap = [
    1: .same(proto: "id", swift: "id"),
    2: .same(proto: "ip", swift: "ip"),
    3: .same(proto: "port", swift: "port"),
    4: .same(proto: "host", swift: "host"),
    5: .unique(proto: "initialized_time", json: "initializedTime", swift: "initializedTime"),
    6: .same(proto: "state", swift: "state"),
    7: .same(proto: "task", swift: "task"),
    8: .same(proto: "dag", swift: "dag"),
    9: .unique(proto: "minutes_before_task_reset", json: "minutesBeforeTaskReset", swift: "minutesBeforeTaskReset"),
    10: .unique(proto: "task_start_time", json: "taskStartTime", swift: "taskStartTime"),
    11: .unique(proto: "os_bit_version", json: "osBitVersion", swift: "osBitVersion"),
    12: .unique(proto: "os_type_version", json: "osTypeVersion", swift: "osTypeVersion"),
    13: .unique(proto: "os_major_version", json: "osMajorVersion", swift: "osMajorVersion"),
    14: .unique(proto: "os_minor_version", json: "osMinorVersion", swift: "osMinorVersion"),
    15: .unique(proto: "os_build_version", json: "osBuildVersion", swift: "osBuildVersion"),
    16: .same(proto: "properties", swift: "properties"),
  ]

  private class _StorageClass {
    typealias ExtendedMessage = Org_Roylance_Yadel_WorkerConfiguration
    var _id: String = ""
    var _ip: String = ""
    var _port: String = ""
    var _host: String = ""
    var _initializedTime: String = ""
    var _state: Org_Roylance_Yadel_WorkerState = Org_Roylance_Yadel_WorkerState.working
    var _task: Org_Roylance_Yadel_Task? = nil
    var _dag: Org_Roylance_Yadel_Dag? = nil
    var _minutesBeforeTaskReset: UInt64 = 0
    var _taskStartTime: String = ""
    var _osBitVersion: Org_Roylance_Yadel_OSBitVersion = Org_Roylance_Yadel_OSBitVersion.v64BitVersion
    var _osTypeVersion: Org_Roylance_Yadel_OSTypeVersion = Org_Roylance_Yadel_OSTypeVersion.macOsTypeVersion
    var _osMajorVersion: String = ""
    var _osMinorVersion: String = ""
    var _osBuildVersion: String = ""
    var _properties: [Org_Roylance_Yadel_WorkerProperty] = []

    init() {}

    func decodeField<T: SwiftProtobuf.FieldDecoder>(setter: inout T, protoFieldNumber: Int) throws {
      switch protoFieldNumber {
      case 1: try setter.decodeSingularField(fieldType: SwiftProtobuf.ProtobufString.self, value: &_id)
      case 2: try setter.decodeSingularField(fieldType: SwiftProtobuf.ProtobufString.self, value: &_ip)
      case 3: try setter.decodeSingularField(fieldType: SwiftProtobuf.ProtobufString.self, value: &_port)
      case 4: try setter.decodeSingularField(fieldType: SwiftProtobuf.ProtobufString.self, value: &_host)
      case 5: try setter.decodeSingularField(fieldType: SwiftProtobuf.ProtobufString.self, value: &_initializedTime)
      case 6: try setter.decodeSingularField(fieldType: Org_Roylance_Yadel_WorkerState.self, value: &_state)
      case 7: try setter.decodeSingularMessageField(fieldType: Org_Roylance_Yadel_Task.self, value: &_task)
      case 8: try setter.decodeSingularMessageField(fieldType: Org_Roylance_Yadel_Dag.self, value: &_dag)
      case 9: try setter.decodeSingularField(fieldType: SwiftProtobuf.ProtobufUInt64.self, value: &_minutesBeforeTaskReset)
      case 10: try setter.decodeSingularField(fieldType: SwiftProtobuf.ProtobufString.self, value: &_taskStartTime)
      case 11: try setter.decodeSingularField(fieldType: Org_Roylance_Yadel_OSBitVersion.self, value: &_osBitVersion)
      case 12: try setter.decodeSingularField(fieldType: Org_Roylance_Yadel_OSTypeVersion.self, value: &_osTypeVersion)
      case 13: try setter.decodeSingularField(fieldType: SwiftProtobuf.ProtobufString.self, value: &_osMajorVersion)
      case 14: try setter.decodeSingularField(fieldType: SwiftProtobuf.ProtobufString.self, value: &_osMinorVersion)
      case 15: try setter.decodeSingularField(fieldType: SwiftProtobuf.ProtobufString.self, value: &_osBuildVersion)
      case 16: try setter.decodeRepeatedMessageField(fieldType: Org_Roylance_Yadel_WorkerProperty.self, value: &_properties)
      default: break
      }
    }

    func traverse(visitor: SwiftProtobuf.Visitor) throws {
      if _id != "" {
        try visitor.visitSingularField(fieldType: SwiftProtobuf.ProtobufString.self, value: _id, fieldNumber: 1)
      }
      if _ip != "" {
        try visitor.visitSingularField(fieldType: SwiftProtobuf.ProtobufString.self, value: _ip, fieldNumber: 2)
      }
      if _port != "" {
        try visitor.visitSingularField(fieldType: SwiftProtobuf.ProtobufString.self, value: _port, fieldNumber: 3)
      }
      if _host != "" {
        try visitor.visitSingularField(fieldType: SwiftProtobuf.ProtobufString.self, value: _host, fieldNumber: 4)
      }
      if _initializedTime != "" {
        try visitor.visitSingularField(fieldType: SwiftProtobuf.ProtobufString.self, value: _initializedTime, fieldNumber: 5)
      }
      if _state != Org_Roylance_Yadel_WorkerState.working {
        try visitor.visitSingularField(fieldType: Org_Roylance_Yadel_WorkerState.self, value: _state, fieldNumber: 6)
      }
      if let v = _task {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 7)
      }
      if let v = _dag {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 8)
      }
      if _minutesBeforeTaskReset != 0 {
        try visitor.visitSingularField(fieldType: SwiftProtobuf.ProtobufUInt64.self, value: _minutesBeforeTaskReset, fieldNumber: 9)
      }
      if _taskStartTime != "" {
        try visitor.visitSingularField(fieldType: SwiftProtobuf.ProtobufString.self, value: _taskStartTime, fieldNumber: 10)
      }
      if _osBitVersion != Org_Roylance_Yadel_OSBitVersion.v64BitVersion {
        try visitor.visitSingularField(fieldType: Org_Roylance_Yadel_OSBitVersion.self, value: _osBitVersion, fieldNumber: 11)
      }
      if _osTypeVersion != Org_Roylance_Yadel_OSTypeVersion.macOsTypeVersion {
        try visitor.visitSingularField(fieldType: Org_Roylance_Yadel_OSTypeVersion.self, value: _osTypeVersion, fieldNumber: 12)
      }
      if _osMajorVersion != "" {
        try visitor.visitSingularField(fieldType: SwiftProtobuf.ProtobufString.self, value: _osMajorVersion, fieldNumber: 13)
      }
      if _osMinorVersion != "" {
        try visitor.visitSingularField(fieldType: SwiftProtobuf.ProtobufString.self, value: _osMinorVersion, fieldNumber: 14)
      }
      if _osBuildVersion != "" {
        try visitor.visitSingularField(fieldType: SwiftProtobuf.ProtobufString.self, value: _osBuildVersion, fieldNumber: 15)
      }
      if !_properties.isEmpty {
        try visitor.visitRepeatedMessageField(value: _properties, fieldNumber: 16)
      }
    }

    func isEqualTo(other: _StorageClass) -> Bool {
      if _id != other._id {return false}
      if _ip != other._ip {return false}
      if _port != other._port {return false}
      if _host != other._host {return false}
      if _initializedTime != other._initializedTime {return false}
      if _state != other._state {return false}
      if _task != other._task {return false}
      if _dag != other._dag {return false}
      if _minutesBeforeTaskReset != other._minutesBeforeTaskReset {return false}
      if _taskStartTime != other._taskStartTime {return false}
      if _osBitVersion != other._osBitVersion {return false}
      if _osTypeVersion != other._osTypeVersion {return false}
      if _osMajorVersion != other._osMajorVersion {return false}
      if _osMinorVersion != other._osMinorVersion {return false}
      if _osBuildVersion != other._osBuildVersion {return false}
      if _properties != other._properties {return false}
      return true
    }

    func copy() -> _StorageClass {
      let clone = _StorageClass()
      clone._id = _id
      clone._ip = _ip
      clone._port = _port
      clone._host = _host
      clone._initializedTime = _initializedTime
      clone._state = _state
      clone._task = _task
      clone._dag = _dag
      clone._minutesBeforeTaskReset = _minutesBeforeTaskReset
      clone._taskStartTime = _taskStartTime
      clone._osBitVersion = _osBitVersion
      clone._osTypeVersion = _osTypeVersion
      clone._osMajorVersion = _osMajorVersion
      clone._osMinorVersion = _osMinorVersion
      clone._osBuildVersion = _osBuildVersion
      clone._properties = _properties
      return clone
    }
  }

  private var _storage = _StorageClass()


  public var id: String {
    get {return _storage._id}
    set {_uniqueStorage()._id = newValue}
  }

  public var ip: String {
    get {return _storage._ip}
    set {_uniqueStorage()._ip = newValue}
  }

  public var port: String {
    get {return _storage._port}
    set {_uniqueStorage()._port = newValue}
  }

  public var host: String {
    get {return _storage._host}
    set {_uniqueStorage()._host = newValue}
  }

  public var initializedTime: String {
    get {return _storage._initializedTime}
    set {_uniqueStorage()._initializedTime = newValue}
  }

  public var state: Org_Roylance_Yadel_WorkerState {
    get {return _storage._state}
    set {_uniqueStorage()._state = newValue}
  }

  public var task: Org_Roylance_Yadel_Task {
    get {return _storage._task ?? Org_Roylance_Yadel_Task()}
    set {_uniqueStorage()._task = newValue}
  }
  public var hasTask: Bool {
    return _storage._task != nil
  }
  public mutating func clearTask() {
    return _storage._task = nil
  }

  public var dag: Org_Roylance_Yadel_Dag {
    get {return _storage._dag ?? Org_Roylance_Yadel_Dag()}
    set {_uniqueStorage()._dag = newValue}
  }
  public var hasDag: Bool {
    return _storage._dag != nil
  }
  public mutating func clearDag() {
    return _storage._dag = nil
  }

  public var minutesBeforeTaskReset: UInt64 {
    get {return _storage._minutesBeforeTaskReset}
    set {_uniqueStorage()._minutesBeforeTaskReset = newValue}
  }

  public var taskStartTime: String {
    get {return _storage._taskStartTime}
    set {_uniqueStorage()._taskStartTime = newValue}
  }

  public var osBitVersion: Org_Roylance_Yadel_OSBitVersion {
    get {return _storage._osBitVersion}
    set {_uniqueStorage()._osBitVersion = newValue}
  }

  public var osTypeVersion: Org_Roylance_Yadel_OSTypeVersion {
    get {return _storage._osTypeVersion}
    set {_uniqueStorage()._osTypeVersion = newValue}
  }

  public var osMajorVersion: String {
    get {return _storage._osMajorVersion}
    set {_uniqueStorage()._osMajorVersion = newValue}
  }

  public var osMinorVersion: String {
    get {return _storage._osMinorVersion}
    set {_uniqueStorage()._osMinorVersion = newValue}
  }

  public var osBuildVersion: String {
    get {return _storage._osBuildVersion}
    set {_uniqueStorage()._osBuildVersion = newValue}
  }

  public var properties: [Org_Roylance_Yadel_WorkerProperty] {
    get {return _storage._properties}
    set {_uniqueStorage()._properties = newValue}
  }

  public init() {}

  public mutating func _protoc_generated_decodeField<T: SwiftProtobuf.FieldDecoder>(setter: inout T, protoFieldNumber: Int) throws {
    try _uniqueStorage().decodeField(setter: &setter, protoFieldNumber: protoFieldNumber)
  }

  public func _protoc_generated_traverse(visitor: SwiftProtobuf.Visitor) throws {
    try _storage.traverse(visitor: visitor)
  }

  public func _protoc_generated_isEqualTo(other: Org_Roylance_Yadel_WorkerConfiguration) -> Bool {
    return _storage === other._storage || _storage.isEqualTo(other: other._storage)
  }

  private mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _storage.copy()
    }
    return _storage
  }
}

public struct Org_Roylance_Yadel_Log: SwiftProtobuf.Message, SwiftProtobuf.Proto3Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf.ProtoNameProviding {
  public var swiftClassName: String {return "Org_Roylance_Yadel_Log"}
  public var protoMessageName: String {return "Log"}
  public var protoPackageName: String {return "org.roylance.yadel"}
  public static let _protobuf_fieldNames: FieldNameMap = [
    1: .same(proto: "id", swift: "id"),
    2: .same(proto: "message", swift: "message"),
  ]


  public var id: String = ""

  public var message: String = ""

  public init() {}

  public mutating func _protoc_generated_decodeField<T: SwiftProtobuf.FieldDecoder>(setter: inout T, protoFieldNumber: Int) throws {
    switch protoFieldNumber {
    case 1: try setter.decodeSingularField(fieldType: SwiftProtobuf.ProtobufString.self, value: &id)
    case 2: try setter.decodeSingularField(fieldType: SwiftProtobuf.ProtobufString.self, value: &message)
    default: break
    }
  }

  public func _protoc_generated_traverse(visitor: SwiftProtobuf.Visitor) throws {
    if id != "" {
      try visitor.visitSingularField(fieldType: SwiftProtobuf.ProtobufString.self, value: id, fieldNumber: 1)
    }
    if message != "" {
      try visitor.visitSingularField(fieldType: SwiftProtobuf.ProtobufString.self, value: message, fieldNumber: 2)
    }
  }

  public func _protoc_generated_isEqualTo(other: Org_Roylance_Yadel_Log) -> Bool {
    if id != other.id {return false}
    if message != other.message {return false}
    return true
  }
}

public struct Org_Roylance_Yadel_Dag: SwiftProtobuf.Message, SwiftProtobuf.Proto3Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf.ProtoNameProviding {
  public var swiftClassName: String {return "Org_Roylance_Yadel_Dag"}
  public var protoMessageName: String {return "Dag"}
  public var protoPackageName: String {return "org.roylance.yadel"}
  public static let _protobuf_fieldNames: FieldNameMap = [
    1: .same(proto: "id", swift: "id"),
    2: .same(proto: "display", swift: "display"),
    3: .unique(proto: "flattened_tasks", json: "flattenedTasks", swift: "flattenedTasks"),
    4: .unique(proto: "execution_date", json: "executionDate", swift: "executionDate"),
    5: .unique(proto: "start_date", json: "startDate", swift: "startDate"),
    6: .unique(proto: "end_date", json: "endDate", swift: "endDate"),
    7: .same(proto: "duration", swift: "duration"),
    8: .unique(proto: "uncompleted_tasks", json: "uncompletedTasks", swift: "uncompletedTasks"),
    9: .unique(proto: "processing_tasks", json: "processingTasks", swift: "processingTasks"),
    10: .unique(proto: "errored_tasks", json: "erroredTasks", swift: "erroredTasks"),
    11: .unique(proto: "completed_tasks", json: "completedTasks", swift: "completedTasks"),
    12: .same(proto: "parent", swift: "parent"),
  ]

  private class _StorageClass {
    typealias ExtendedMessage = Org_Roylance_Yadel_Dag
    var _id: String = ""
    var _display: String = ""
    var _flattenedTasks: [Org_Roylance_Yadel_Task] = []
    var _executionDate: Int64 = 0
    var _startDate: Int64 = 0
    var _endDate: Int64 = 0
    var _duration: Int64 = 0
    var _uncompletedTasks: [Org_Roylance_Yadel_Task] = []
    var _processingTasks: [Org_Roylance_Yadel_Task] = []
    var _erroredTasks: [Org_Roylance_Yadel_Task] = []
    var _completedTasks: [Org_Roylance_Yadel_Task] = []
    var _parent: Org_Roylance_Yadel_Dag? = nil

    init() {}

    func decodeField<T: SwiftProtobuf.FieldDecoder>(setter: inout T, protoFieldNumber: Int) throws {
      switch protoFieldNumber {
      case 1: try setter.decodeSingularField(fieldType: SwiftProtobuf.ProtobufString.self, value: &_id)
      case 2: try setter.decodeSingularField(fieldType: SwiftProtobuf.ProtobufString.self, value: &_display)
      case 3: try setter.decodeRepeatedMessageField(fieldType: Org_Roylance_Yadel_Task.self, value: &_flattenedTasks)
      case 4: try setter.decodeSingularField(fieldType: SwiftProtobuf.ProtobufInt64.self, value: &_executionDate)
      case 5: try setter.decodeSingularField(fieldType: SwiftProtobuf.ProtobufInt64.self, value: &_startDate)
      case 6: try setter.decodeSingularField(fieldType: SwiftProtobuf.ProtobufInt64.self, value: &_endDate)
      case 7: try setter.decodeSingularField(fieldType: SwiftProtobuf.ProtobufInt64.self, value: &_duration)
      case 8: try setter.decodeRepeatedMessageField(fieldType: Org_Roylance_Yadel_Task.self, value: &_uncompletedTasks)
      case 9: try setter.decodeRepeatedMessageField(fieldType: Org_Roylance_Yadel_Task.self, value: &_processingTasks)
      case 10: try setter.decodeRepeatedMessageField(fieldType: Org_Roylance_Yadel_Task.self, value: &_erroredTasks)
      case 11: try setter.decodeRepeatedMessageField(fieldType: Org_Roylance_Yadel_Task.self, value: &_completedTasks)
      case 12: try setter.decodeSingularMessageField(fieldType: Org_Roylance_Yadel_Dag.self, value: &_parent)
      default: break
      }
    }

    func traverse(visitor: SwiftProtobuf.Visitor) throws {
      if _id != "" {
        try visitor.visitSingularField(fieldType: SwiftProtobuf.ProtobufString.self, value: _id, fieldNumber: 1)
      }
      if _display != "" {
        try visitor.visitSingularField(fieldType: SwiftProtobuf.ProtobufString.self, value: _display, fieldNumber: 2)
      }
      if !_flattenedTasks.isEmpty {
        try visitor.visitRepeatedMessageField(value: _flattenedTasks, fieldNumber: 3)
      }
      if _executionDate != 0 {
        try visitor.visitSingularField(fieldType: SwiftProtobuf.ProtobufInt64.self, value: _executionDate, fieldNumber: 4)
      }
      if _startDate != 0 {
        try visitor.visitSingularField(fieldType: SwiftProtobuf.ProtobufInt64.self, value: _startDate, fieldNumber: 5)
      }
      if _endDate != 0 {
        try visitor.visitSingularField(fieldType: SwiftProtobuf.ProtobufInt64.self, value: _endDate, fieldNumber: 6)
      }
      if _duration != 0 {
        try visitor.visitSingularField(fieldType: SwiftProtobuf.ProtobufInt64.self, value: _duration, fieldNumber: 7)
      }
      if !_uncompletedTasks.isEmpty {
        try visitor.visitRepeatedMessageField(value: _uncompletedTasks, fieldNumber: 8)
      }
      if !_processingTasks.isEmpty {
        try visitor.visitRepeatedMessageField(value: _processingTasks, fieldNumber: 9)
      }
      if !_erroredTasks.isEmpty {
        try visitor.visitRepeatedMessageField(value: _erroredTasks, fieldNumber: 10)
      }
      if !_completedTasks.isEmpty {
        try visitor.visitRepeatedMessageField(value: _completedTasks, fieldNumber: 11)
      }
      if let v = _parent {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 12)
      }
    }

    func isEqualTo(other: _StorageClass) -> Bool {
      if _id != other._id {return false}
      if _display != other._display {return false}
      if _flattenedTasks != other._flattenedTasks {return false}
      if _executionDate != other._executionDate {return false}
      if _startDate != other._startDate {return false}
      if _endDate != other._endDate {return false}
      if _duration != other._duration {return false}
      if _uncompletedTasks != other._uncompletedTasks {return false}
      if _processingTasks != other._processingTasks {return false}
      if _erroredTasks != other._erroredTasks {return false}
      if _completedTasks != other._completedTasks {return false}
      if _parent != other._parent {return false}
      return true
    }

    func copy() -> _StorageClass {
      let clone = _StorageClass()
      clone._id = _id
      clone._display = _display
      clone._flattenedTasks = _flattenedTasks
      clone._executionDate = _executionDate
      clone._startDate = _startDate
      clone._endDate = _endDate
      clone._duration = _duration
      clone._uncompletedTasks = _uncompletedTasks
      clone._processingTasks = _processingTasks
      clone._erroredTasks = _erroredTasks
      clone._completedTasks = _completedTasks
      clone._parent = _parent
      return clone
    }
  }

  private var _storage = _StorageClass()


  public var id: String {
    get {return _storage._id}
    set {_uniqueStorage()._id = newValue}
  }

  public var display: String {
    get {return _storage._display}
    set {_uniqueStorage()._display = newValue}
  }

  public var flattenedTasks: [Org_Roylance_Yadel_Task] {
    get {return _storage._flattenedTasks}
    set {_uniqueStorage()._flattenedTasks = newValue}
  }

  public var executionDate: Int64 {
    get {return _storage._executionDate}
    set {_uniqueStorage()._executionDate = newValue}
  }

  public var startDate: Int64 {
    get {return _storage._startDate}
    set {_uniqueStorage()._startDate = newValue}
  }

  public var endDate: Int64 {
    get {return _storage._endDate}
    set {_uniqueStorage()._endDate = newValue}
  }

  public var duration: Int64 {
    get {return _storage._duration}
    set {_uniqueStorage()._duration = newValue}
  }

  public var uncompletedTasks: [Org_Roylance_Yadel_Task] {
    get {return _storage._uncompletedTasks}
    set {_uniqueStorage()._uncompletedTasks = newValue}
  }

  public var processingTasks: [Org_Roylance_Yadel_Task] {
    get {return _storage._processingTasks}
    set {_uniqueStorage()._processingTasks = newValue}
  }

  public var erroredTasks: [Org_Roylance_Yadel_Task] {
    get {return _storage._erroredTasks}
    set {_uniqueStorage()._erroredTasks = newValue}
  }

  public var completedTasks: [Org_Roylance_Yadel_Task] {
    get {return _storage._completedTasks}
    set {_uniqueStorage()._completedTasks = newValue}
  }

  public var parent: Org_Roylance_Yadel_Dag {
    get {return _storage._parent ?? Org_Roylance_Yadel_Dag()}
    set {_uniqueStorage()._parent = newValue}
  }
  public var hasParent: Bool {
    return _storage._parent != nil
  }
  public mutating func clearParent() {
    return _storage._parent = nil
  }

  public init() {}

  public mutating func _protoc_generated_decodeField<T: SwiftProtobuf.FieldDecoder>(setter: inout T, protoFieldNumber: Int) throws {
    try _uniqueStorage().decodeField(setter: &setter, protoFieldNumber: protoFieldNumber)
  }

  public func _protoc_generated_traverse(visitor: SwiftProtobuf.Visitor) throws {
    try _storage.traverse(visitor: visitor)
  }

  public func _protoc_generated_isEqualTo(other: Org_Roylance_Yadel_Dag) -> Bool {
    return _storage === other._storage || _storage.isEqualTo(other: other._storage)
  }

  private mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _storage.copy()
    }
    return _storage
  }
}

public struct Org_Roylance_Yadel_Task: SwiftProtobuf.Message, SwiftProtobuf.Proto3Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf.ProtoNameProviding {
  public var swiftClassName: String {return "Org_Roylance_Yadel_Task"}
  public var protoMessageName: String {return "Task"}
  public var protoPackageName: String {return "org.roylance.yadel"}
  public static let _protobuf_fieldNames: FieldNameMap = [
    1: .same(proto: "id", swift: "id"),
    2: .same(proto: "display", swift: "display"),
    3: .same(proto: "dependencies", swift: "dependencies"),
    4: .unique(proto: "dag_id", json: "dagId", swift: "dagId"),
    5: .same(proto: "logs", swift: "logs"),
    6: .unique(proto: "execution_date", json: "executionDate", swift: "executionDate"),
    7: .unique(proto: "start_date", json: "startDate", swift: "startDate"),
    8: .unique(proto: "end_date", json: "endDate", swift: "endDate"),
    9: .same(proto: "duration", swift: "duration"),
    10: .unique(proto: "first_context_base_64", json: "firstContextBase64", swift: "firstContextBase64"),
    11: .unique(proto: "second_context_base_64", json: "secondContextBase64", swift: "secondContextBase64"),
    12: .unique(proto: "third_context_base_64", json: "thirdContextBase64", swift: "thirdContextBase64"),
    13: .unique(proto: "is_waiting_for_another_dag_task", json: "isWaitingForAnotherDagTask", swift: "isWaitingForAnotherDagTask"),
    14: .same(proto: "filters", swift: "filters"),
  ]


  public var id: String = ""

  public var display: String = ""

  public var dependencies: [Org_Roylance_Yadel_TaskDependency] = []

  public var dagId: String = ""

  public var logs: [Org_Roylance_Yadel_Log] = []

  public var executionDate: Int64 = 0

  public var startDate: Int64 = 0

  public var endDate: Int64 = 0

  public var duration: Int64 = 0

  public var firstContextBase64: String = ""

  public var secondContextBase64: String = ""

  public var thirdContextBase64: String = ""

  public var isWaitingForAnotherDagTask: Bool = false

  public var filters: [Org_Roylance_Yadel_WorkerFilter] = []

  public init() {}

  public mutating func _protoc_generated_decodeField<T: SwiftProtobuf.FieldDecoder>(setter: inout T, protoFieldNumber: Int) throws {
    switch protoFieldNumber {
    case 1: try setter.decodeSingularField(fieldType: SwiftProtobuf.ProtobufString.self, value: &id)
    case 2: try setter.decodeSingularField(fieldType: SwiftProtobuf.ProtobufString.self, value: &display)
    case 3: try setter.decodeRepeatedMessageField(fieldType: Org_Roylance_Yadel_TaskDependency.self, value: &dependencies)
    case 4: try setter.decodeSingularField(fieldType: SwiftProtobuf.ProtobufString.self, value: &dagId)
    case 5: try setter.decodeRepeatedMessageField(fieldType: Org_Roylance_Yadel_Log.self, value: &logs)
    case 6: try setter.decodeSingularField(fieldType: SwiftProtobuf.ProtobufInt64.self, value: &executionDate)
    case 7: try setter.decodeSingularField(fieldType: SwiftProtobuf.ProtobufInt64.self, value: &startDate)
    case 8: try setter.decodeSingularField(fieldType: SwiftProtobuf.ProtobufInt64.self, value: &endDate)
    case 9: try setter.decodeSingularField(fieldType: SwiftProtobuf.ProtobufInt64.self, value: &duration)
    case 10: try setter.decodeSingularField(fieldType: SwiftProtobuf.ProtobufString.self, value: &firstContextBase64)
    case 11: try setter.decodeSingularField(fieldType: SwiftProtobuf.ProtobufString.self, value: &secondContextBase64)
    case 12: try setter.decodeSingularField(fieldType: SwiftProtobuf.ProtobufString.self, value: &thirdContextBase64)
    case 13: try setter.decodeSingularField(fieldType: SwiftProtobuf.ProtobufBool.self, value: &isWaitingForAnotherDagTask)
    case 14: try setter.decodeRepeatedMessageField(fieldType: Org_Roylance_Yadel_WorkerFilter.self, value: &filters)
    default: break
    }
  }

  public func _protoc_generated_traverse(visitor: SwiftProtobuf.Visitor) throws {
    if id != "" {
      try visitor.visitSingularField(fieldType: SwiftProtobuf.ProtobufString.self, value: id, fieldNumber: 1)
    }
    if display != "" {
      try visitor.visitSingularField(fieldType: SwiftProtobuf.ProtobufString.self, value: display, fieldNumber: 2)
    }
    if !dependencies.isEmpty {
      try visitor.visitRepeatedMessageField(value: dependencies, fieldNumber: 3)
    }
    if dagId != "" {
      try visitor.visitSingularField(fieldType: SwiftProtobuf.ProtobufString.self, value: dagId, fieldNumber: 4)
    }
    if !logs.isEmpty {
      try visitor.visitRepeatedMessageField(value: logs, fieldNumber: 5)
    }
    if executionDate != 0 {
      try visitor.visitSingularField(fieldType: SwiftProtobuf.ProtobufInt64.self, value: executionDate, fieldNumber: 6)
    }
    if startDate != 0 {
      try visitor.visitSingularField(fieldType: SwiftProtobuf.ProtobufInt64.self, value: startDate, fieldNumber: 7)
    }
    if endDate != 0 {
      try visitor.visitSingularField(fieldType: SwiftProtobuf.ProtobufInt64.self, value: endDate, fieldNumber: 8)
    }
    if duration != 0 {
      try visitor.visitSingularField(fieldType: SwiftProtobuf.ProtobufInt64.self, value: duration, fieldNumber: 9)
    }
    if firstContextBase64 != "" {
      try visitor.visitSingularField(fieldType: SwiftProtobuf.ProtobufString.self, value: firstContextBase64, fieldNumber: 10)
    }
    if secondContextBase64 != "" {
      try visitor.visitSingularField(fieldType: SwiftProtobuf.ProtobufString.self, value: secondContextBase64, fieldNumber: 11)
    }
    if thirdContextBase64 != "" {
      try visitor.visitSingularField(fieldType: SwiftProtobuf.ProtobufString.self, value: thirdContextBase64, fieldNumber: 12)
    }
    if isWaitingForAnotherDagTask != false {
      try visitor.visitSingularField(fieldType: SwiftProtobuf.ProtobufBool.self, value: isWaitingForAnotherDagTask, fieldNumber: 13)
    }
    if !filters.isEmpty {
      try visitor.visitRepeatedMessageField(value: filters, fieldNumber: 14)
    }
  }

  public func _protoc_generated_isEqualTo(other: Org_Roylance_Yadel_Task) -> Bool {
    if id != other.id {return false}
    if display != other.display {return false}
    if dependencies != other.dependencies {return false}
    if dagId != other.dagId {return false}
    if logs != other.logs {return false}
    if executionDate != other.executionDate {return false}
    if startDate != other.startDate {return false}
    if endDate != other.endDate {return false}
    if duration != other.duration {return false}
    if firstContextBase64 != other.firstContextBase64 {return false}
    if secondContextBase64 != other.secondContextBase64 {return false}
    if thirdContextBase64 != other.thirdContextBase64 {return false}
    if isWaitingForAnotherDagTask != other.isWaitingForAnotherDagTask {return false}
    if filters != other.filters {return false}
    return true
  }
}

public struct Org_Roylance_Yadel_TaskDependency: SwiftProtobuf.Message, SwiftProtobuf.Proto3Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf.ProtoNameProviding {
  public var swiftClassName: String {return "Org_Roylance_Yadel_TaskDependency"}
  public var protoMessageName: String {return "TaskDependency"}
  public var protoPackageName: String {return "org.roylance.yadel"}
  public static let _protobuf_fieldNames: FieldNameMap = [
    1: .same(proto: "id", swift: "id"),
    2: .unique(proto: "parent_task_id", json: "parentTaskId", swift: "parentTaskId"),
  ]


  public var id: String = ""

  public var parentTaskId: String = ""

  public init() {}

  public mutating func _protoc_generated_decodeField<T: SwiftProtobuf.FieldDecoder>(setter: inout T, protoFieldNumber: Int) throws {
    switch protoFieldNumber {
    case 1: try setter.decodeSingularField(fieldType: SwiftProtobuf.ProtobufString.self, value: &id)
    case 2: try setter.decodeSingularField(fieldType: SwiftProtobuf.ProtobufString.self, value: &parentTaskId)
    default: break
    }
  }

  public func _protoc_generated_traverse(visitor: SwiftProtobuf.Visitor) throws {
    if id != "" {
      try visitor.visitSingularField(fieldType: SwiftProtobuf.ProtobufString.self, value: id, fieldNumber: 1)
    }
    if parentTaskId != "" {
      try visitor.visitSingularField(fieldType: SwiftProtobuf.ProtobufString.self, value: parentTaskId, fieldNumber: 2)
    }
  }

  public func _protoc_generated_isEqualTo(other: Org_Roylance_Yadel_TaskDependency) -> Bool {
    if id != other.id {return false}
    if parentTaskId != other.parentTaskId {return false}
    return true
  }
}

public struct Org_Roylance_Yadel_AddTaskToDag: SwiftProtobuf.Message, SwiftProtobuf.Proto3Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf.ProtoNameProviding {
  public var swiftClassName: String {return "Org_Roylance_Yadel_AddTaskToDag"}
  public var protoMessageName: String {return "AddTaskToDag"}
  public var protoPackageName: String {return "org.roylance.yadel"}
  public static let _protobuf_fieldNames: FieldNameMap = [
    1: .same(proto: "id", swift: "id"),
    2: .unique(proto: "parent_task", json: "parentTask", swift: "parentTask"),
    3: .unique(proto: "new_task", json: "newTask", swift: "newTask"),
    4: .unique(proto: "first_context_base_64", json: "firstContextBase64", swift: "firstContextBase64"),
    5: .unique(proto: "second_context_base_64", json: "secondContextBase64", swift: "secondContextBase64"),
    6: .unique(proto: "third_context_base_64", json: "thirdContextBase64", swift: "thirdContextBase64"),
  ]

  private class _StorageClass {
    typealias ExtendedMessage = Org_Roylance_Yadel_AddTaskToDag
    var _id: String = ""
    var _parentTask: Org_Roylance_Yadel_Task? = nil
    var _newTask: Org_Roylance_Yadel_Task? = nil
    var _firstContextBase64: String = ""
    var _secondContextBase64: String = ""
    var _thirdContextBase64: String = ""

    init() {}

    func decodeField<T: SwiftProtobuf.FieldDecoder>(setter: inout T, protoFieldNumber: Int) throws {
      switch protoFieldNumber {
      case 1: try setter.decodeSingularField(fieldType: SwiftProtobuf.ProtobufString.self, value: &_id)
      case 2: try setter.decodeSingularMessageField(fieldType: Org_Roylance_Yadel_Task.self, value: &_parentTask)
      case 3: try setter.decodeSingularMessageField(fieldType: Org_Roylance_Yadel_Task.self, value: &_newTask)
      case 4: try setter.decodeSingularField(fieldType: SwiftProtobuf.ProtobufString.self, value: &_firstContextBase64)
      case 5: try setter.decodeSingularField(fieldType: SwiftProtobuf.ProtobufString.self, value: &_secondContextBase64)
      case 6: try setter.decodeSingularField(fieldType: SwiftProtobuf.ProtobufString.self, value: &_thirdContextBase64)
      default: break
      }
    }

    func traverse(visitor: SwiftProtobuf.Visitor) throws {
      if _id != "" {
        try visitor.visitSingularField(fieldType: SwiftProtobuf.ProtobufString.self, value: _id, fieldNumber: 1)
      }
      if let v = _parentTask {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
      }
      if let v = _newTask {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
      }
      if _firstContextBase64 != "" {
        try visitor.visitSingularField(fieldType: SwiftProtobuf.ProtobufString.self, value: _firstContextBase64, fieldNumber: 4)
      }
      if _secondContextBase64 != "" {
        try visitor.visitSingularField(fieldType: SwiftProtobuf.ProtobufString.self, value: _secondContextBase64, fieldNumber: 5)
      }
      if _thirdContextBase64 != "" {
        try visitor.visitSingularField(fieldType: SwiftProtobuf.ProtobufString.self, value: _thirdContextBase64, fieldNumber: 6)
      }
    }

    func isEqualTo(other: _StorageClass) -> Bool {
      if _id != other._id {return false}
      if _parentTask != other._parentTask {return false}
      if _newTask != other._newTask {return false}
      if _firstContextBase64 != other._firstContextBase64 {return false}
      if _secondContextBase64 != other._secondContextBase64 {return false}
      if _thirdContextBase64 != other._thirdContextBase64 {return false}
      return true
    }

    func copy() -> _StorageClass {
      let clone = _StorageClass()
      clone._id = _id
      clone._parentTask = _parentTask
      clone._newTask = _newTask
      clone._firstContextBase64 = _firstContextBase64
      clone._secondContextBase64 = _secondContextBase64
      clone._thirdContextBase64 = _thirdContextBase64
      return clone
    }
  }

  private var _storage = _StorageClass()


  public var id: String {
    get {return _storage._id}
    set {_uniqueStorage()._id = newValue}
  }

  public var parentTask: Org_Roylance_Yadel_Task {
    get {return _storage._parentTask ?? Org_Roylance_Yadel_Task()}
    set {_uniqueStorage()._parentTask = newValue}
  }
  public var hasParentTask: Bool {
    return _storage._parentTask != nil
  }
  public mutating func clearParentTask() {
    return _storage._parentTask = nil
  }

  public var newTask: Org_Roylance_Yadel_Task {
    get {return _storage._newTask ?? Org_Roylance_Yadel_Task()}
    set {_uniqueStorage()._newTask = newValue}
  }
  public var hasNewTask: Bool {
    return _storage._newTask != nil
  }
  public mutating func clearNewTask() {
    return _storage._newTask = nil
  }

  public var firstContextBase64: String {
    get {return _storage._firstContextBase64}
    set {_uniqueStorage()._firstContextBase64 = newValue}
  }

  public var secondContextBase64: String {
    get {return _storage._secondContextBase64}
    set {_uniqueStorage()._secondContextBase64 = newValue}
  }

  public var thirdContextBase64: String {
    get {return _storage._thirdContextBase64}
    set {_uniqueStorage()._thirdContextBase64 = newValue}
  }

  public init() {}

  public mutating func _protoc_generated_decodeField<T: SwiftProtobuf.FieldDecoder>(setter: inout T, protoFieldNumber: Int) throws {
    try _uniqueStorage().decodeField(setter: &setter, protoFieldNumber: protoFieldNumber)
  }

  public func _protoc_generated_traverse(visitor: SwiftProtobuf.Visitor) throws {
    try _storage.traverse(visitor: visitor)
  }

  public func _protoc_generated_isEqualTo(other: Org_Roylance_Yadel_AddTaskToDag) -> Bool {
    return _storage === other._storage || _storage.isEqualTo(other: other._storage)
  }

  private mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _storage.copy()
    }
    return _storage
  }
}

public struct Org_Roylance_Yadel_CompleteTask: SwiftProtobuf.Message, SwiftProtobuf.Proto3Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf.ProtoNameProviding {
  public var swiftClassName: String {return "Org_Roylance_Yadel_CompleteTask"}
  public var protoMessageName: String {return "CompleteTask"}
  public var protoPackageName: String {return "org.roylance.yadel"}
  public static let _protobuf_fieldNames: FieldNameMap = [
    1: .same(proto: "id", swift: "id"),
    2: .same(proto: "task", swift: "task"),
    3: .unique(proto: "worker_configuration", json: "workerConfiguration", swift: "workerConfiguration"),
    5: .unique(proto: "is_error", json: "isError", swift: "isError"),
  ]

  private class _StorageClass {
    typealias ExtendedMessage = Org_Roylance_Yadel_CompleteTask
    var _id: String = ""
    var _task: Org_Roylance_Yadel_Task? = nil
    var _workerConfiguration: Org_Roylance_Yadel_WorkerConfiguration? = nil
    var _isError: Bool = false

    init() {}

    func decodeField<T: SwiftProtobuf.FieldDecoder>(setter: inout T, protoFieldNumber: Int) throws {
      switch protoFieldNumber {
      case 1: try setter.decodeSingularField(fieldType: SwiftProtobuf.ProtobufString.self, value: &_id)
      case 2: try setter.decodeSingularMessageField(fieldType: Org_Roylance_Yadel_Task.self, value: &_task)
      case 3: try setter.decodeSingularMessageField(fieldType: Org_Roylance_Yadel_WorkerConfiguration.self, value: &_workerConfiguration)
      case 5: try setter.decodeSingularField(fieldType: SwiftProtobuf.ProtobufBool.self, value: &_isError)
      default: break
      }
    }

    func traverse(visitor: SwiftProtobuf.Visitor) throws {
      if _id != "" {
        try visitor.visitSingularField(fieldType: SwiftProtobuf.ProtobufString.self, value: _id, fieldNumber: 1)
      }
      if let v = _task {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
      }
      if let v = _workerConfiguration {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
      }
      if _isError != false {
        try visitor.visitSingularField(fieldType: SwiftProtobuf.ProtobufBool.self, value: _isError, fieldNumber: 5)
      }
    }

    func isEqualTo(other: _StorageClass) -> Bool {
      if _id != other._id {return false}
      if _task != other._task {return false}
      if _workerConfiguration != other._workerConfiguration {return false}
      if _isError != other._isError {return false}
      return true
    }

    func copy() -> _StorageClass {
      let clone = _StorageClass()
      clone._id = _id
      clone._task = _task
      clone._workerConfiguration = _workerConfiguration
      clone._isError = _isError
      return clone
    }
  }

  private var _storage = _StorageClass()


  public var id: String {
    get {return _storage._id}
    set {_uniqueStorage()._id = newValue}
  }

  public var task: Org_Roylance_Yadel_Task {
    get {return _storage._task ?? Org_Roylance_Yadel_Task()}
    set {_uniqueStorage()._task = newValue}
  }
  public var hasTask: Bool {
    return _storage._task != nil
  }
  public mutating func clearTask() {
    return _storage._task = nil
  }

  public var workerConfiguration: Org_Roylance_Yadel_WorkerConfiguration {
    get {return _storage._workerConfiguration ?? Org_Roylance_Yadel_WorkerConfiguration()}
    set {_uniqueStorage()._workerConfiguration = newValue}
  }
  public var hasWorkerConfiguration: Bool {
    return _storage._workerConfiguration != nil
  }
  public mutating func clearWorkerConfiguration() {
    return _storage._workerConfiguration = nil
  }

  public var isError: Bool {
    get {return _storage._isError}
    set {_uniqueStorage()._isError = newValue}
  }

  public init() {}

  public mutating func _protoc_generated_decodeField<T: SwiftProtobuf.FieldDecoder>(setter: inout T, protoFieldNumber: Int) throws {
    try _uniqueStorage().decodeField(setter: &setter, protoFieldNumber: protoFieldNumber)
  }

  public func _protoc_generated_traverse(visitor: SwiftProtobuf.Visitor) throws {
    try _storage.traverse(visitor: visitor)
  }

  public func _protoc_generated_isEqualTo(other: Org_Roylance_Yadel_CompleteTask) -> Bool {
    return _storage === other._storage || _storage.isEqualTo(other: other._storage)
  }

  private mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _storage.copy()
    }
    return _storage
  }
}

public struct Org_Roylance_Yadel_AllDags: SwiftProtobuf.Message, SwiftProtobuf.Proto3Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf.ProtoNameProviding {
  public var swiftClassName: String {return "Org_Roylance_Yadel_AllDags"}
  public var protoMessageName: String {return "AllDags"}
  public var protoPackageName: String {return "org.roylance.yadel"}
  public static let _protobuf_fieldNames: FieldNameMap = [
    1: .same(proto: "dags", swift: "dags"),
    2: .same(proto: "workers", swift: "workers"),
    3: .unique(proto: "include_unprocessed", json: "includeUnprocessed", swift: "includeUnprocessed"),
    4: .unique(proto: "include_file_saved", json: "includeFileSaved", swift: "includeFileSaved"),
  ]


  public var dags: [Org_Roylance_Yadel_Dag] = []

  public var workers: [Org_Roylance_Yadel_WorkerConfiguration] = []

  public var includeUnprocessed: Bool = false

  public var includeFileSaved: Bool = false

  public init() {}

  public mutating func _protoc_generated_decodeField<T: SwiftProtobuf.FieldDecoder>(setter: inout T, protoFieldNumber: Int) throws {
    switch protoFieldNumber {
    case 1: try setter.decodeRepeatedMessageField(fieldType: Org_Roylance_Yadel_Dag.self, value: &dags)
    case 2: try setter.decodeRepeatedMessageField(fieldType: Org_Roylance_Yadel_WorkerConfiguration.self, value: &workers)
    case 3: try setter.decodeSingularField(fieldType: SwiftProtobuf.ProtobufBool.self, value: &includeUnprocessed)
    case 4: try setter.decodeSingularField(fieldType: SwiftProtobuf.ProtobufBool.self, value: &includeFileSaved)
    default: break
    }
  }

  public func _protoc_generated_traverse(visitor: SwiftProtobuf.Visitor) throws {
    if !dags.isEmpty {
      try visitor.visitRepeatedMessageField(value: dags, fieldNumber: 1)
    }
    if !workers.isEmpty {
      try visitor.visitRepeatedMessageField(value: workers, fieldNumber: 2)
    }
    if includeUnprocessed != false {
      try visitor.visitSingularField(fieldType: SwiftProtobuf.ProtobufBool.self, value: includeUnprocessed, fieldNumber: 3)
    }
    if includeFileSaved != false {
      try visitor.visitSingularField(fieldType: SwiftProtobuf.ProtobufBool.self, value: includeFileSaved, fieldNumber: 4)
    }
  }

  public func _protoc_generated_isEqualTo(other: Org_Roylance_Yadel_AllDags) -> Bool {
    if dags != other.dags {return false}
    if workers != other.workers {return false}
    if includeUnprocessed != other.includeUnprocessed {return false}
    if includeFileSaved != other.includeFileSaved {return false}
    return true
  }
}

public struct Org_Roylance_Yadel_WorkerProperties: SwiftProtobuf.Message, SwiftProtobuf.Proto3Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf.ProtoNameProviding {
  public var swiftClassName: String {return "Org_Roylance_Yadel_WorkerProperties"}
  public var protoMessageName: String {return "WorkerProperties"}
  public var protoPackageName: String {return "org.roylance.yadel"}
  public static let _protobuf_fieldNames: FieldNameMap = [
    1: .same(proto: "id", swift: "id"),
    2: .unique(proto: "os_bit_version", json: "osBitVersion", swift: "osBitVersion"),
    3: .unique(proto: "os_type_version", json: "osTypeVersion", swift: "osTypeVersion"),
    4: .unique(proto: "os_major_version", json: "osMajorVersion", swift: "osMajorVersion"),
    5: .unique(proto: "os_minor_version", json: "osMinorVersion", swift: "osMinorVersion"),
    6: .unique(proto: "os_build_version", json: "osBuildVersion", swift: "osBuildVersion"),
    7: .same(proto: "properties", swift: "properties"),
  ]


  public var id: String = ""

  public var osBitVersion: Org_Roylance_Yadel_OSBitVersion = Org_Roylance_Yadel_OSBitVersion.v64BitVersion

  public var osTypeVersion: Org_Roylance_Yadel_OSTypeVersion = Org_Roylance_Yadel_OSTypeVersion.macOsTypeVersion

  public var osMajorVersion: String = ""

  public var osMinorVersion: String = ""

  public var osBuildVersion: String = ""

  public var properties: [Org_Roylance_Yadel_WorkerProperty] = []

  public init() {}

  public mutating func _protoc_generated_decodeField<T: SwiftProtobuf.FieldDecoder>(setter: inout T, protoFieldNumber: Int) throws {
    switch protoFieldNumber {
    case 1: try setter.decodeSingularField(fieldType: SwiftProtobuf.ProtobufString.self, value: &id)
    case 2: try setter.decodeSingularField(fieldType: Org_Roylance_Yadel_OSBitVersion.self, value: &osBitVersion)
    case 3: try setter.decodeSingularField(fieldType: Org_Roylance_Yadel_OSTypeVersion.self, value: &osTypeVersion)
    case 4: try setter.decodeSingularField(fieldType: SwiftProtobuf.ProtobufString.self, value: &osMajorVersion)
    case 5: try setter.decodeSingularField(fieldType: SwiftProtobuf.ProtobufString.self, value: &osMinorVersion)
    case 6: try setter.decodeSingularField(fieldType: SwiftProtobuf.ProtobufString.self, value: &osBuildVersion)
    case 7: try setter.decodeRepeatedMessageField(fieldType: Org_Roylance_Yadel_WorkerProperty.self, value: &properties)
    default: break
    }
  }

  public func _protoc_generated_traverse(visitor: SwiftProtobuf.Visitor) throws {
    if id != "" {
      try visitor.visitSingularField(fieldType: SwiftProtobuf.ProtobufString.self, value: id, fieldNumber: 1)
    }
    if osBitVersion != Org_Roylance_Yadel_OSBitVersion.v64BitVersion {
      try visitor.visitSingularField(fieldType: Org_Roylance_Yadel_OSBitVersion.self, value: osBitVersion, fieldNumber: 2)
    }
    if osTypeVersion != Org_Roylance_Yadel_OSTypeVersion.macOsTypeVersion {
      try visitor.visitSingularField(fieldType: Org_Roylance_Yadel_OSTypeVersion.self, value: osTypeVersion, fieldNumber: 3)
    }
    if osMajorVersion != "" {
      try visitor.visitSingularField(fieldType: SwiftProtobuf.ProtobufString.self, value: osMajorVersion, fieldNumber: 4)
    }
    if osMinorVersion != "" {
      try visitor.visitSingularField(fieldType: SwiftProtobuf.ProtobufString.self, value: osMinorVersion, fieldNumber: 5)
    }
    if osBuildVersion != "" {
      try visitor.visitSingularField(fieldType: SwiftProtobuf.ProtobufString.self, value: osBuildVersion, fieldNumber: 6)
    }
    if !properties.isEmpty {
      try visitor.visitRepeatedMessageField(value: properties, fieldNumber: 7)
    }
  }

  public func _protoc_generated_isEqualTo(other: Org_Roylance_Yadel_WorkerProperties) -> Bool {
    if id != other.id {return false}
    if osBitVersion != other.osBitVersion {return false}
    if osTypeVersion != other.osTypeVersion {return false}
    if osMajorVersion != other.osMajorVersion {return false}
    if osMinorVersion != other.osMinorVersion {return false}
    if osBuildVersion != other.osBuildVersion {return false}
    if properties != other.properties {return false}
    return true
  }
}
